cp ~/pdb/mmCIF/av/1avo.cif.gz cif
cp ~/pdb/mmCIF/b0/1b0u.cif.gz cif
cp ~/pdb/mmCIF/b6/1b68.cif.gz cif
cp ~/pdb/mmCIF/bm/1bmf.cif.gz cif
cp ~/pdb/mmCIF/bz/1bz4.cif.gz cif
cp ~/pdb/mmCIF/c1/1c17.cif.gz cif
cp ~/pdb/mmCIF/c9/1c9k.cif.gz cif
cp ~/pdb/mmCIF/cb/1cbu.cif.gz cif
cp ~/pdb/mmCIF/ci/1cii.cif.gz cif
cp ~/pdb/mmCIF/co/1cow.cif.gz cif
cp ~/pdb/mmCIF/cr/1cr0.cif.gz cif
cp ~/pdb/mmCIF/cr/1cr1.cif.gz cif
cp ~/pdb/mmCIF/cr/1cr2.cif.gz cif
cp ~/pdb/mmCIF/cr/1cr4.cif.gz cif
cp ~/pdb/mmCIF/d2/1d2n.cif.gz cif
cp ~/pdb/mmCIF/d8/1d8s.cif.gz cif
cp ~/pdb/mmCIF/do/1dow.cif.gz cif
cp ~/pdb/mmCIF/e0/1e0j.cif.gz cif
cp ~/pdb/mmCIF/e0/1e0k.cif.gz cif
cp ~/pdb/mmCIF/e1/1e1q.cif.gz cif
cp ~/pdb/mmCIF/e1/1e1r.cif.gz cif
cp ~/pdb/mmCIF/e3/1e32.cif.gz cif
cp ~/pdb/mmCIF/e3/1e3m.cif.gz cif
cp ~/pdb/mmCIF/e6/1e69.cif.gz cif
cp ~/pdb/mmCIF/e7/1e79.cif.gz cif
cp ~/pdb/mmCIF/e8/1e84.cif.gz cif
cp ~/pdb/mmCIF/e9/1e94.cif.gz cif
cp ~/pdb/mmCIF/e9/1e9r.cif.gz cif
cp ~/pdb/mmCIF/e9/1e9s.cif.gz cif
cp ~/pdb/mmCIF/ea/1ea8.cif.gz cif
cp ~/pdb/mmCIF/ef/1efr.cif.gz cif
cp ~/pdb/mmCIF/ew/1ewq.cif.gz cif
cp ~/pdb/mmCIF/ew/1ewr.cif.gz cif
cp ~/pdb/mmCIF/f2/1f2t.cif.gz cif
cp ~/pdb/mmCIF/f3/1f3o.cif.gz cif
cp ~/pdb/mmCIF/ff/1fft.cif.gz cif
cp ~/pdb/mmCIF/fn/1fnn.cif.gz cif
cp ~/pdb/mmCIF/fw/1fw6.cif.gz cif
cp ~/pdb/mmCIF/fx/1fx0.cif.gz cif
cp ~/pdb/mmCIF/fx/1fxk.cif.gz cif
cp ~/pdb/mmCIF/g2/1g29.cif.gz cif
cp ~/pdb/mmCIF/g4/1g4a.cif.gz cif
cp ~/pdb/mmCIF/g5/1g5r.cif.gz cif
cp ~/pdb/mmCIF/g6/1g64.cif.gz cif
cp ~/pdb/mmCIF/g6/1g6h.cif.gz cif
cp ~/pdb/mmCIF/g6/1g6o.cif.gz cif
cp ~/pdb/mmCIF/g8/1g8p.cif.gz cif
cp ~/pdb/mmCIF/g8/1g8y.cif.gz cif
cp ~/pdb/mmCIF/g9/1g9x.cif.gz cif
cp ~/pdb/mmCIF/ga/1gaj.cif.gz cif
cp ~/pdb/mmCIF/ga/1gax.cif.gz cif
cp ~/pdb/mmCIF/gm/1gm5.cif.gz cif
cp ~/pdb/mmCIF/gs/1gs9.cif.gz cif
cp ~/pdb/mmCIF/h6/1h6g.cif.gz cif
cp ~/pdb/mmCIF/h7/1h7i.cif.gz cif
cp ~/pdb/mmCIF/h8/1h8e.cif.gz cif
cp ~/pdb/mmCIF/h8/1h8h.cif.gz cif
cp ~/pdb/mmCIF/i4/1i49.cif.gz cif
cp ~/pdb/mmCIF/i4/1i4t.cif.gz cif
cp ~/pdb/mmCIF/ii/1ii8.cif.gz cif
cp ~/pdb/mmCIF/in/1in5.cif.gz cif
cp ~/pdb/mmCIF/iq/1iqp.cif.gz cif
cp ~/pdb/mmCIF/ix/1ixs.cif.gz cif
cp ~/pdb/mmCIF/jb/1jbk.cif.gz cif
cp ~/pdb/mmCIF/ji/1ji0.cif.gz cif
cp ~/pdb/mmCIF/jj/1jj7.cif.gz cif
cp ~/pdb/mmCIF/jn/1jnv.cif.gz cif
cp ~/pdb/mmCIF/jq/1jqj.cif.gz cif
cp ~/pdb/mmCIF/jr/1jr3.cif.gz cif
cp ~/pdb/mmCIF/k0/1k04.cif.gz cif
cp ~/pdb/mmCIF/k3/1k33.cif.gz cif
cp ~/pdb/mmCIF/km/1kmh.cif.gz cif
cp ~/pdb/mmCIF/km/1kmi.cif.gz cif
cp ~/pdb/mmCIF/ku/1ku9.cif.gz cif
cp ~/pdb/mmCIF/l2/1l2t.cif.gz cif
cp ~/pdb/mmCIF/l7/1l7v.cif.gz cif
cp ~/pdb/mmCIF/l8/1l8q.cif.gz cif
cp ~/pdb/mmCIF/le/1le2.cif.gz cif
cp ~/pdb/mmCIF/le/1le4.cif.gz cif
cp ~/pdb/mmCIF/lp/1lpe.cif.gz cif
cp ~/pdb/mmCIF/m5/1m56.cif.gz cif
cp ~/pdb/mmCIF/m6/1m6t.cif.gz cif
cp ~/pdb/mmCIF/ma/1mab.cif.gz cif
cp ~/pdb/mmCIF/mo/1mo3.cif.gz cif
cp ~/pdb/mmCIF/mo/1mo4.cif.gz cif
cp ~/pdb/mmCIF/mo/1mo6.cif.gz cif
cp ~/pdb/mmCIF/mt/1mt0.cif.gz cif
cp ~/pdb/mmCIF/mv/1mv5.cif.gz cif
cp ~/pdb/mmCIF/n0/1n0w.cif.gz cif
cp ~/pdb/mmCIF/nb/1nbm.cif.gz cif
cp ~/pdb/mmCIF/nf/1nfn.cif.gz cif
cp ~/pdb/mmCIF/nf/1nfo.cif.gz cif
cp ~/pdb/mmCIF/ng/1ng9.cif.gz cif
cp ~/pdb/mmCIF/nl/1nlf.cif.gz cif
cp ~/pdb/mmCIF/nl/1nlz.cif.gz cif
cp ~/pdb/mmCIF/nn/1nne.cif.gz cif
cp ~/pdb/mmCIF/np/1np6.cif.gz cif
cp ~/pdb/mmCIF/ny/1ny5.cif.gz cif
cp ~/pdb/mmCIF/nz/1nze.cif.gz cif
cp ~/pdb/mmCIF/oc/1occ.cif.gz cif
cp ~/pdb/mmCIF/oc/1ocz.cif.gz cif
cp ~/pdb/mmCIF/of/1oft.cif.gz cif
cp ~/pdb/mmCIF/oh/1oh5.cif.gz cif
cp ~/pdb/mmCIF/oh/1oh6.cif.gz cif
cp ~/pdb/mmCIF/oh/1oh7.cif.gz cif
cp ~/pdb/mmCIF/oh/1oh8.cif.gz cif
cp ~/pdb/mmCIF/oj/1ojl.cif.gz cif
cp ~/pdb/mmCIF/ol/1olo.cif.gz cif
cp ~/pdb/mmCIF/or/1or3.cif.gz cif
cp ~/pdb/mmCIF/ox/1oxs.cif.gz cif
cp ~/pdb/mmCIF/ox/1oxt.cif.gz cif
cp ~/pdb/mmCIF/ox/1oxu.cif.gz cif
cp ~/pdb/mmCIF/ox/1oxv.cif.gz cif
cp ~/pdb/mmCIF/ox/1oxx.cif.gz cif
cp ~/pdb/mmCIF/p9/1p9r.cif.gz cif
cp ~/pdb/mmCIF/p9/1p9w.cif.gz cif
cp ~/pdb/mmCIF/pj/1pjr.cif.gz cif
cp ~/pdb/mmCIF/pv/1pv4.cif.gz cif
cp ~/pdb/mmCIF/pv/1pvo.cif.gz cif
cp ~/pdb/mmCIF/q1/1q12.cif.gz cif
cp ~/pdb/mmCIF/q1/1q1b.cif.gz cif
cp ~/pdb/mmCIF/q1/1q1e.cif.gz cif
cp ~/pdb/mmCIF/q3/1q3h.cif.gz cif
cp ~/pdb/mmCIF/q5/1q57.cif.gz cif
cp ~/pdb/mmCIF/qk/1qkr.cif.gz cif
cp ~/pdb/mmCIF/qu/1qu7.cif.gz cif
cp ~/pdb/mmCIF/r0/1r0w.cif.gz cif
cp ~/pdb/mmCIF/r0/1r0x.cif.gz cif
cp ~/pdb/mmCIF/r0/1r0y.cif.gz cif
cp ~/pdb/mmCIF/r0/1r0z.cif.gz cif
cp ~/pdb/mmCIF/r1/1r10.cif.gz cif
cp ~/pdb/mmCIF/rc/1rcp.cif.gz cif
cp ~/pdb/mmCIF/ri/1rif.cif.gz cif
cp ~/pdb/mmCIF/sj/1sj8.cif.gz cif
cp ~/pdb/mmCIF/sk/1skv.cif.gz cif
cp ~/pdb/mmCIF/sk/1sky.cif.gz cif
cp ~/pdb/mmCIF/st/1st6.cif.gz cif
cp ~/pdb/mmCIF/sx/1sxj.cif.gz cif
cp ~/pdb/mmCIF/sz/1szi.cif.gz cif
cp ~/pdb/mmCIF/sz/1szp.cif.gz cif
cp ~/pdb/mmCIF/t4/1t4g.cif.gz cif
cp ~/pdb/mmCIF/tf/1tf7.cif.gz cif
cp ~/pdb/mmCIF/u2/1u2m.cif.gz cif
cp ~/pdb/mmCIF/u9/1u94.cif.gz cif
cp ~/pdb/mmCIF/u9/1u98.cif.gz cif
cp ~/pdb/mmCIF/u9/1u99.cif.gz cif
cp ~/pdb/mmCIF/u9/1u9i.cif.gz cif
cp ~/pdb/mmCIF/ua/1uaa.cif.gz cif
cp ~/pdb/mmCIF/ub/1ubc.cif.gz cif
cp ~/pdb/mmCIF/ub/1ube.cif.gz cif
cp ~/pdb/mmCIF/ub/1ubg.cif.gz cif
cp ~/pdb/mmCIF/ur/1uru.cif.gz cif
cp ~/pdb/mmCIF/v4/1v43.cif.gz cif
cp ~/pdb/mmCIF/v5/1v5w.cif.gz cif
cp ~/pdb/mmCIF/vc/1vci.cif.gz cif
cp ~/pdb/mmCIF/vd/1vdz.cif.gz cif
cp ~/pdb/mmCIF/vp/1vpl.cif.gz cif
cp ~/pdb/mmCIF/w0/1w0j.cif.gz cif
cp ~/pdb/mmCIF/w0/1w0k.cif.gz cif
cp ~/pdb/mmCIF/w1/1w1w.cif.gz cif
cp ~/pdb/mmCIF/w3/1w36.cif.gz cif
cp ~/pdb/mmCIF/w4/1w44.cif.gz cif
cp ~/pdb/mmCIF/w4/1w4r.cif.gz cif
cp ~/pdb/mmCIF/w5/1w5s.cif.gz cif
cp ~/pdb/mmCIF/w7/1w7a.cif.gz cif
cp ~/pdb/mmCIF/wb/1wb9.cif.gz cif
cp ~/pdb/mmCIF/wb/1wbb.cif.gz cif
cp ~/pdb/mmCIF/wb/1wbd.cif.gz cif
cp ~/pdb/mmCIF/wd/1wdf.cif.gz cif
cp ~/pdb/mmCIF/wd/1wdg.cif.gz cif
cp ~/pdb/mmCIF/wp/1wp1.cif.gz cif
cp ~/pdb/mmCIF/wp/1wp9.cif.gz cif
cp ~/pdb/mmCIF/xe/1xef.cif.gz cif
cp ~/pdb/mmCIF/xe/1xew.cif.gz cif
cp ~/pdb/mmCIF/xe/1xex.cif.gz cif
cp ~/pdb/mmCIF/xf/1xf9.cif.gz cif
cp ~/pdb/mmCIF/xf/1xfa.cif.gz cif
cp ~/pdb/mmCIF/xm/1xmi.cif.gz cif
cp ~/pdb/mmCIF/xm/1xmj.cif.gz cif
cp ~/pdb/mmCIF/xm/1xms.cif.gz cif
cp ~/pdb/mmCIF/xm/1xmv.cif.gz cif
cp ~/pdb/mmCIF/xp/1xp8.cif.gz cif
cp ~/pdb/mmCIF/xp/1xpo.cif.gz cif
cp ~/pdb/mmCIF/xt/1xtj.cif.gz cif
cp ~/pdb/mmCIF/xu/1xu4.cif.gz cif
cp ~/pdb/mmCIF/xw/1xwi.cif.gz cif
cp ~/pdb/mmCIF/xx/1xx6.cif.gz cif
cp ~/pdb/mmCIF/ya/1ya9.cif.gz cif
cp ~/pdb/mmCIF/ye/1ye8.cif.gz cif
cp ~/pdb/mmCIF/yg/1yg2.cif.gz cif
cp ~/pdb/mmCIF/yo/1yo7.cif.gz cif
cp ~/pdb/mmCIF/yq/1yqt.cif.gz cif
cp ~/pdb/mmCIF/z4/1z47.cif.gz cif
cp ~/pdb/mmCIF/zv/1zva.cif.gz cif
cp ~/pdb/mmCIF/a0/2a01.cif.gz cif
cp ~/pdb/mmCIF/ap/2ap3.cif.gz cif
cp ~/pdb/mmCIF/aw/2awn.cif.gz cif
cp ~/pdb/mmCIF/aw/2awo.cif.gz cif
cp ~/pdb/mmCIF/ax/2axt.cif.gz cif
cp ~/pdb/mmCIF/b2/2b21.cif.gz cif
cp ~/pdb/mmCIF/bb/2bbo.cif.gz cif
cp ~/pdb/mmCIF/bb/2bbs.cif.gz cif
cp ~/pdb/mmCIF/bb/2bbt.cif.gz cif
cp ~/pdb/mmCIF/bd/2bde.cif.gz cif
cp ~/pdb/mmCIF/bk/2bke.cif.gz cif
cp ~/pdb/mmCIF/c6/2c61.cif.gz cif
cp ~/pdb/mmCIF/cb/2cbz.cif.gz cif
cp ~/pdb/mmCIF/cc/2ccy.cif.gz cif
cp ~/pdb/mmCIF/ce/2ce7.cif.gz cif
cp ~/pdb/mmCIF/ch/2ch7.cif.gz cif
cp ~/pdb/mmCIF/ch/2chg.cif.gz cif
cp ~/pdb/mmCIF/ch/2chq.cif.gz cif
cp ~/pdb/mmCIF/ck/2ck3.cif.gz cif
cp ~/pdb/mmCIF/cv/2cvf.cif.gz cif
cp ~/pdb/mmCIF/cv/2cvh.cif.gz cif
cp ~/pdb/mmCIF/d2/2d2e.cif.gz cif
cp ~/pdb/mmCIF/d2/2d2f.cif.gz cif
cp ~/pdb/mmCIF/d3/2d3w.cif.gz cif
cp ~/pdb/mmCIF/d4/2d4u.cif.gz cif
cp ~/pdb/mmCIF/d6/2d62.cif.gz cif
cp ~/pdb/mmCIF/d7/2d7d.cif.gz cif
cp ~/pdb/mmCIF/de/2de0.cif.gz cif
cp ~/pdb/mmCIF/df/2dfl.cif.gz cif
cp ~/pdb/mmCIF/dh/2dhr.cif.gz cif
cp ~/pdb/mmCIF/dp/2dpy.cif.gz cif
cp ~/pdb/mmCIF/dr/2dr3.cif.gz cif
cp ~/pdb/mmCIF/e8/2e87.cif.gz cif
cp ~/pdb/mmCIF/ek/2ekd.cif.gz cif
cp ~/pdb/mmCIF/et/2etd.cif.gz cif
cp ~/pdb/mmCIF/ew/2ewv.cif.gz cif
cp ~/pdb/mmCIF/ey/2eyq.cif.gz cif
cp ~/pdb/mmCIF/f1/2f1h.cif.gz cif
cp ~/pdb/mmCIF/f1/2f1i.cif.gz cif
cp ~/pdb/mmCIF/f1/2f1j.cif.gz cif
cp ~/pdb/mmCIF/f1/2f1m.cif.gz cif
cp ~/pdb/mmCIF/fb/2fb5.cif.gz cif
cp ~/pdb/mmCIF/fd/2fdc.cif.gz cif
cp ~/pdb/mmCIF/ff/2ff7.cif.gz cif
cp ~/pdb/mmCIF/ff/2ffa.cif.gz cif
cp ~/pdb/mmCIF/ff/2ffb.cif.gz cif
cp ~/pdb/mmCIF/fg/2fgj.cif.gz cif
cp ~/pdb/mmCIF/fg/2fgk.cif.gz cif
cp ~/pdb/mmCIF/fn/2fna.cif.gz cif
cp ~/pdb/mmCIF/fp/2fpk.cif.gz cif
cp ~/pdb/mmCIF/fp/2fpl.cif.gz cif
cp ~/pdb/mmCIF/fp/2fpm.cif.gz cif
cp ~/pdb/mmCIF/fz/2fzl.cif.gz cif
cp ~/pdb/mmCIF/g8/2g88.cif.gz cif
cp ~/pdb/mmCIF/gb/2gbl.cif.gz cif
cp ~/pdb/mmCIF/gd/2gd5.cif.gz cif
cp ~/pdb/mmCIF/gd/2gdj.cif.gz cif
cp ~/pdb/mmCIF/gh/2ghi.cif.gz cif
cp ~/pdb/mmCIF/gn/2gno.cif.gz cif
cp ~/pdb/mmCIF/gz/2gza.cif.gz cif
cp ~/pdb/mmCIF/hl/2hld.cif.gz cif
cp ~/pdb/mmCIF/hu/2huj.cif.gz cif
cp ~/pdb/mmCIF/hy/2hyd.cif.gz cif
cp ~/pdb/mmCIF/i1/2i1k.cif.gz cif
cp ~/pdb/mmCIF/i1/2i1q.cif.gz cif
cp ~/pdb/mmCIF/ie/2ieq.cif.gz cif
cp ~/pdb/mmCIF/ih/2ihy.cif.gz cif
cp ~/pdb/mmCIF/is/2is4.cif.gz cif
cp ~/pdb/mmCIF/is/2is6.cif.gz cif
cp ~/pdb/mmCIF/it/2it1.cif.gz cif
cp ~/pdb/mmCIF/iu/2ius.cif.gz cif
cp ~/pdb/mmCIF/iu/2iut.cif.gz cif
cp ~/pdb/mmCIF/iw/2iw3.cif.gz cif
cp ~/pdb/mmCIF/iw/2iwh.cif.gz cif
cp ~/pdb/mmCIF/ix/2ix3.cif.gz cif
cp ~/pdb/mmCIF/ix/2ix8.cif.gz cif
cp ~/pdb/mmCIF/ix/2ixe.cif.gz cif
cp ~/pdb/mmCIF/ix/2ixf.cif.gz cif
cp ~/pdb/mmCIF/ix/2ixg.cif.gz cif
cp ~/pdb/mmCIF/iz/2izp.cif.gz cif
cp ~/pdb/mmCIF/j8/2j87.cif.gz cif
cp ~/pdb/mmCIF/ja/2ja1.cif.gz cif
cp ~/pdb/mmCIF/ji/2jiz.cif.gz cif
cp ~/pdb/mmCIF/jj/2jj1.cif.gz cif
cp ~/pdb/mmCIF/jj/2jj2.cif.gz cif
cp ~/pdb/mmCIF/jl/2jlu.cif.gz cif
cp ~/pdb/mmCIF/jl/2jlv.cif.gz cif
cp ~/pdb/mmCIF/jl/2jlw.cif.gz cif
cp ~/pdb/mmCIF/jl/2jlx.cif.gz cif
cp ~/pdb/mmCIF/jl/2jly.cif.gz cif
cp ~/pdb/mmCIF/jx/2jx0.cif.gz cif
cp ~/pdb/mmCIF/kb/2kbb.cif.gz cif
cp ~/pdb/mmCIF/kc/2kc3.cif.gz cif
cp ~/pdb/mmCIF/kv/2kvp.cif.gz cif
cp ~/pdb/mmCIF/l1/2l10.cif.gz cif
cp ~/pdb/mmCIF/l6/2l6f.cif.gz cif
cp ~/pdb/mmCIF/l7/2l7b.cif.gz cif
cp ~/pdb/mmCIF/l7/2l7n.cif.gz cif
cp ~/pdb/mmCIF/l8/2l81.cif.gz cif
cp ~/pdb/mmCIF/mn/2mn2.cif.gz cif
cp ~/pdb/mmCIF/mw/2mwq.cif.gz cif
cp ~/pdb/mmCIF/nq/2nq2.cif.gz cif
cp ~/pdb/mmCIF/o5/2o5v.cif.gz cif
cp ~/pdb/mmCIF/o8/2o8b.cif.gz cif
cp ~/pdb/mmCIF/o8/2o8c.cif.gz cif
cp ~/pdb/mmCIF/o8/2o8d.cif.gz cif
cp ~/pdb/mmCIF/o8/2o8e.cif.gz cif
cp ~/pdb/mmCIF/o8/2o8f.cif.gz cif
cp ~/pdb/mmCIF/oa/2oap.cif.gz cif
cp ~/pdb/mmCIF/ob/2obl.cif.gz cif
cp ~/pdb/mmCIF/oc/2oca.cif.gz cif
cp ~/pdb/mmCIF/od/2odn.cif.gz cif
cp ~/pdb/mmCIF/oe/2oe2.cif.gz cif
cp ~/pdb/mmCIF/oe/2oep.cif.gz cif
cp ~/pdb/mmCIF/oe/2oes.cif.gz cif
cp ~/pdb/mmCIF/of/2ofo.cif.gz cif
cp ~/pdb/mmCIF/ol/2olj.cif.gz cif
cp ~/pdb/mmCIF/ol/2olk.cif.gz cif
cp ~/pdb/mmCIF/on/2onj.cif.gz cif
cp ~/pdb/mmCIF/on/2onk.cif.gz cif
cp ~/pdb/mmCIF/or/2orw.cif.gz cif
cp ~/pdb/mmCIF/ou/2ouk.cif.gz cif
cp ~/pdb/mmCIF/p0/2p01.cif.gz cif
cp ~/pdb/mmCIF/p0/2p0n.cif.gz cif
cp ~/pdb/mmCIF/p2/2p22.cif.gz cif
cp ~/pdb/mmCIF/p6/2p6r.cif.gz cif
cp ~/pdb/mmCIF/pc/2pcj.cif.gz cif
cp ~/pdb/mmCIF/pc/2pcl.cif.gz cif
cp ~/pdb/mmCIF/pj/2pjz.cif.gz cif
cp ~/pdb/mmCIF/pm/2pmk.cif.gz cif
cp ~/pdb/mmCIF/pz/2pze.cif.gz cif
cp ~/pdb/mmCIF/pz/2pzf.cif.gz cif
cp ~/pdb/mmCIF/pz/2pzg.cif.gz cif
cp ~/pdb/mmCIF/q0/2q0h.cif.gz cif
cp ~/pdb/mmCIF/q0/2q0o.cif.gz cif
cp ~/pdb/mmCIF/q6/2q6t.cif.gz cif
cp ~/pdb/mmCIF/qb/2qby.cif.gz cif
cp ~/pdb/mmCIF/qe/2qe7.cif.gz cif
cp ~/pdb/mmCIF/qi/2qi9.cif.gz cif
cp ~/pdb/mmCIF/qz/2qz4.cif.gz cif
cp ~/pdb/mmCIF/r2/2r2a.cif.gz cif
cp ~/pdb/mmCIF/r6/2r65.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6a.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6c.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6d.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6e.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6f.cif.gz cif
cp ~/pdb/mmCIF/r6/2r6g.cif.gz cif
cp ~/pdb/mmCIF/r8/2r8r.cif.gz cif
cp ~/pdb/mmCIF/r9/2r9v.cif.gz cif
cp ~/pdb/mmCIF/re/2reb.cif.gz cif
cp ~/pdb/mmCIF/rk/2rkh.cif.gz cif
cp ~/pdb/mmCIF/rk/2rko.cif.gz cif
cp ~/pdb/mmCIF/rk/2rkw.cif.gz cif
cp ~/pdb/mmCIF/uz/2uz3.cif.gz cif
cp ~/pdb/mmCIF/v0/2v0x.cif.gz cif
cp ~/pdb/mmCIF/vf/2vf7.cif.gz cif
cp ~/pdb/mmCIF/vf/2vf8.cif.gz cif
cp ~/pdb/mmCIF/vi/2vii.cif.gz cif
cp ~/pdb/mmCIF/vl/2vl7.cif.gz cif
cp ~/pdb/mmCIF/vy/2vye.cif.gz cif
cp ~/pdb/mmCIF/vy/2vyf.cif.gz cif
cp ~/pdb/mmCIF/w0/2w0m.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6e.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6f.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6g.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6h.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6i.cif.gz cif
cp ~/pdb/mmCIF/w6/2w6j.cif.gz cif
cp ~/pdb/mmCIF/wj/2wjy.cif.gz cif
cp ~/pdb/mmCIF/wp/2wpd.cif.gz cif
cp ~/pdb/mmCIF/ws/2wss.cif.gz cif
cp ~/pdb/mmCIF/wt/2wtu.cif.gz cif
cp ~/pdb/mmCIF/x2/2x2v.cif.gz cif
cp ~/pdb/mmCIF/x8/2x8a.cif.gz cif
cp ~/pdb/mmCIF/xg/2xgj.cif.gz cif
cp ~/pdb/mmCIF/xn/2xnd.cif.gz cif
cp ~/pdb/mmCIF/xo/2xok.cif.gz cif
cp ~/pdb/mmCIF/xu/2xub.cif.gz cif
cp ~/pdb/mmCIF/y3/2y3a.cif.gz cif
cp ~/pdb/mmCIF/yf/2yfb.cif.gz cif
cp ~/pdb/mmCIF/yy/2yyz.cif.gz cif
cp ~/pdb/mmCIF/yz/2yz2.cif.gz cif
cp ~/pdb/mmCIF/z4/2z43.cif.gz cif
cp ~/pdb/mmCIF/zd/2zdi.cif.gz cif
cp ~/pdb/mmCIF/zj/2zjb.cif.gz cif
cp ~/pdb/mmCIF/zr/2zr0.cif.gz cif
cp ~/pdb/mmCIF/zr/2zr7.cif.gz cif
cp ~/pdb/mmCIF/zr/2zr9.cif.gz cif
cp ~/pdb/mmCIF/zr/2zra.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrb.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrc.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrd.cif.gz cif
cp ~/pdb/mmCIF/zr/2zre.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrf.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrg.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrh.cif.gz cif
cp ~/pdb/mmCIF/zr/2zri.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrj.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrk.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrl.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrm.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrn.cif.gz cif
cp ~/pdb/mmCIF/zr/2zro.cif.gz cif
cp ~/pdb/mmCIF/zr/2zrp.cif.gz cif
cp ~/pdb/mmCIF/zt/2zts.cif.gz cif
cp ~/pdb/mmCIF/zu/2zu0.cif.gz cif
cp ~/pdb/mmCIF/zu/2zub.cif.gz cif
cp ~/pdb/mmCIF/zu/2zuc.cif.gz cif
cp ~/pdb/mmCIF/zu/2zud.cif.gz cif
cp ~/pdb/mmCIF/a5/3a5c.cif.gz cif
cp ~/pdb/mmCIF/a5/3a5d.cif.gz cif
cp ~/pdb/mmCIF/au/3aux.cif.gz cif
cp ~/pdb/mmCIF/au/3auy.cif.gz cif
cp ~/pdb/mmCIF/av/3av0.cif.gz cif
cp ~/pdb/mmCIF/ay/3ayf.cif.gz cif
cp ~/pdb/mmCIF/b2/3b2q.cif.gz cif
cp ~/pdb/mmCIF/b5/3b5j.cif.gz cif
cp ~/pdb/mmCIF/b6/3b60.cif.gz cif
cp ~/pdb/mmCIF/b8/3b85.cif.gz cif
cp ~/pdb/mmCIF/bg/3bgw.cif.gz cif
cp ~/pdb/mmCIF/bh/3bh0.cif.gz cif
cp ~/pdb/mmCIF/bk/3bk7.cif.gz cif
cp ~/pdb/mmCIF/bo/3bos.cif.gz cif
cp ~/pdb/mmCIF/bs/3bs4.cif.gz cif
cp ~/pdb/mmCIF/c3/3c3w.cif.gz cif
cp ~/pdb/mmCIF/c4/3c41.cif.gz cif
cp ~/pdb/mmCIF/c4/3c4j.cif.gz cif
cp ~/pdb/mmCIF/c9/3c98.cif.gz cif
cp ~/pdb/mmCIF/cf/3cf0.cif.gz cif
cp ~/pdb/mmCIF/cf/3cf1.cif.gz cif
cp ~/pdb/mmCIF/cf/3cf2.cif.gz cif
cp ~/pdb/mmCIF/cm/3cmt.cif.gz cif
cp ~/pdb/mmCIF/cm/3cmu.cif.gz cif
cp ~/pdb/mmCIF/cm/3cmv.cif.gz cif
cp ~/pdb/mmCIF/cm/3cmw.cif.gz cif
cp ~/pdb/mmCIF/cm/3cmx.cif.gz cif
cp ~/pdb/mmCIF/cp/3cp1.cif.gz cif
cp ~/pdb/mmCIF/cp/3cpe.cif.gz cif
cp ~/pdb/mmCIF/cr/3crv.cif.gz cif
cp ~/pdb/mmCIF/cy/3cyo.cif.gz cif
cp ~/pdb/mmCIF/d3/3d31.cif.gz cif
cp ~/pdb/mmCIF/d8/3d8b.cif.gz cif
cp ~/pdb/mmCIF/dh/3dhw.cif.gz cif
cp ~/pdb/mmCIF/ds/3dsr.cif.gz cif
cp ~/pdb/mmCIF/dv/3dvl.cif.gz cif
cp ~/pdb/mmCIF/dy/3dyj.cif.gz cif
cp ~/pdb/mmCIF/e2/3e2i.cif.gz cif
cp ~/pdb/mmCIF/ei/3eih.cif.gz cif
cp ~/pdb/mmCIF/ei/3eiu.cif.gz cif
cp ~/pdb/mmCIF/er/3err.cif.gz cif
cp ~/pdb/mmCIF/et/3etv.cif.gz cif
cp ~/pdb/mmCIF/eu/3euj.cif.gz cif
cp ~/pdb/mmCIF/eu/3euk.cif.gz cif
cp ~/pdb/mmCIF/ez/3ezh.cif.gz cif
cp ~/pdb/mmCIF/fd/3fd9.cif.gz cif
cp ~/pdb/mmCIF/fh/3fh6.cif.gz cif
cp ~/pdb/mmCIF/fh/3fhf.cif.gz cif
cp ~/pdb/mmCIF/fk/3fks.cif.gz cif
cp ~/pdb/mmCIF/fv/3fvq.cif.gz cif
cp ~/pdb/mmCIF/g5/3g5u.cif.gz cif
cp ~/pdb/mmCIF/g6/3g60.cif.gz cif
cp ~/pdb/mmCIF/g6/3g61.cif.gz cif
cp ~/pdb/mmCIF/g7/3g7c.cif.gz cif
cp ~/pdb/mmCIF/gd/3gd7.cif.gz cif
cp ~/pdb/mmCIF/gf/3gfo.cif.gz cif
cp ~/pdb/mmCIF/gl/3glf.cif.gz cif
cp ~/pdb/mmCIF/gp/3gp8.cif.gz cif
cp ~/pdb/mmCIF/gq/3gqb.cif.gz cif
cp ~/pdb/mmCIF/ha/3hai.cif.gz cif
cp ~/pdb/mmCIF/hr/3hr0.cif.gz cif
cp ~/pdb/mmCIF/hr/3hr8.cif.gz cif
cp ~/pdb/mmCIF/ib/3ibp.cif.gz cif
cp ~/pdb/mmCIF/ic/3ice.cif.gz cif
cp ~/pdb/mmCIF/ie/3iee.cif.gz cif
cp ~/pdb/mmCIF/io/3io5.cif.gz cif
cp ~/pdb/mmCIF/j0/3j0j.cif.gz cif
cp ~/pdb/mmCIF/j1/3j15.cif.gz cif
cp ~/pdb/mmCIF/j1/3j16.cif.gz cif
cp ~/pdb/mmCIF/j3/3j3r.cif.gz cif
cp ~/pdb/mmCIF/j5/3j5s.cif.gz cif
cp ~/pdb/mmCIF/j9/3j96.cif.gz cif
cp ~/pdb/mmCIF/j9/3j9t.cif.gz cif
cp ~/pdb/mmCIF/j9/3j9u.cif.gz cif
cp ~/pdb/mmCIF/j9/3j9v.cif.gz cif
cp ~/pdb/mmCIF/jv/3jvv.cif.gz cif
cp ~/pdb/mmCIF/jz/3jzm.cif.gz cif
cp ~/pdb/mmCIF/k0/3k09.cif.gz cif
cp ~/pdb/mmCIF/k0/3k0a.cif.gz cif
cp ~/pdb/mmCIF/k0/3k0c.cif.gz cif
cp ~/pdb/mmCIF/k0/3k0e.cif.gz cif
cp ~/pdb/mmCIF/k0/3k0f.cif.gz cif
cp ~/pdb/mmCIF/k0/3k0s.cif.gz cif
cp ~/pdb/mmCIF/k1/3k1j.cif.gz cif
cp ~/pdb/mmCIF/k2/3k29.cif.gz cif
cp ~/pdb/mmCIF/k6/3k66.cif.gz cif
cp ~/pdb/mmCIF/kd/3kdq.cif.gz cif
cp ~/pdb/mmCIF/km/3kmi.cif.gz cif
cp ~/pdb/mmCIF/kt/3kta.cif.gz cif
cp ~/pdb/mmCIF/l0/3l0o.cif.gz cif
cp ~/pdb/mmCIF/l3/3l39.cif.gz cif
cp ~/pdb/mmCIF/l8/3l8i.cif.gz cif
cp ~/pdb/mmCIF/l9/3l9f.cif.gz cif
cp ~/pdb/mmCIF/ls/3ls1.cif.gz cif
cp ~/pdb/mmCIF/ls/3lss.cif.gz cif
cp ~/pdb/mmCIF/ms/3msv.cif.gz cif
cp ~/pdb/mmCIF/mx/3mxz.cif.gz cif
cp ~/pdb/mmCIF/n2/3n27.cif.gz cif
cp ~/pdb/mmCIF/n7/3n70.cif.gz cif
cp ~/pdb/mmCIF/na/3na7.cif.gz cif
cp ~/pdb/mmCIF/nb/3nbx.cif.gz cif
cp ~/pdb/mmCIF/nh/3nh6.cif.gz cif
cp ~/pdb/mmCIF/nh/3nh9.cif.gz cif
cp ~/pdb/mmCIF/nh/3nha.cif.gz cif
cp ~/pdb/mmCIF/nh/3nhb.cif.gz cif
cp ~/pdb/mmCIF/o1/3o1j.cif.gz cif
cp ~/pdb/mmCIF/oa/3oaa.cif.gz cif
cp ~/pdb/mmCIF/oe/3oe7.cif.gz cif
cp ~/pdb/mmCIF/oe/3oee.cif.gz cif
cp ~/pdb/mmCIF/oe/3oeh.cif.gz cif
cp ~/pdb/mmCIF/of/3ofn.cif.gz cif
cp ~/pdb/mmCIF/oz/3ozx.cif.gz cif
cp ~/pdb/mmCIF/p8/3p8c.cif.gz cif
cp ~/pdb/mmCIF/pf/3pf0.cif.gz cif
cp ~/pdb/mmCIF/pi/3pih.cif.gz cif
cp ~/pdb/mmCIF/pj/3pjr.cif.gz cif
cp ~/pdb/mmCIF/pu/3puv.cif.gz cif
cp ~/pdb/mmCIF/pu/3puw.cif.gz cif
cp ~/pdb/mmCIF/pu/3pux.cif.gz cif
cp ~/pdb/mmCIF/pu/3puy.cif.gz cif
cp ~/pdb/mmCIF/pu/3puz.cif.gz cif
cp ~/pdb/mmCIF/pv/3pv0.cif.gz cif
cp ~/pdb/mmCIF/pv/3pvs.cif.gz cif
cp ~/pdb/mmCIF/qf/3qf4.cif.gz cif
cp ~/pdb/mmCIF/qf/3qf7.cif.gz cif
cp ~/pdb/mmCIF/qg/3qg5.cif.gz cif
cp ~/pdb/mmCIF/qh/3qhq.cif.gz cif
cp ~/pdb/mmCIF/qi/3qia.cif.gz cif
cp ~/pdb/mmCIF/qk/3qkr.cif.gz cif
cp ~/pdb/mmCIF/qk/3qks.cif.gz cif
cp ~/pdb/mmCIF/qk/3qkt.cif.gz cif
cp ~/pdb/mmCIF/qk/3qku.cif.gz cif
cp ~/pdb/mmCIF/qm/3qmz.cif.gz cif
cp ~/pdb/mmCIF/qw/3qwe.cif.gz cif
cp ~/pdb/mmCIF/r6/3r6n.cif.gz cif
cp ~/pdb/mmCIF/rc/3rc8.cif.gz cif
cp ~/pdb/mmCIF/rf/3rfy.cif.gz cif
cp ~/pdb/mmCIF/rl/3rlf.cif.gz cif
cp ~/pdb/mmCIF/s1/3s1a.cif.gz cif
cp ~/pdb/mmCIF/s5/3s5u.cif.gz cif
cp ~/pdb/mmCIF/si/3si7.cif.gz cif
cp ~/pdb/mmCIF/ss/3ssa.cif.gz cif
cp ~/pdb/mmCIF/sy/3syk.cif.gz cif
cp ~/pdb/mmCIF/t6/3t6g.cif.gz cif
cp ~/pdb/mmCIF/te/3teq.cif.gz cif
cp ~/pdb/mmCIF/tg/3tgw.cif.gz cif
cp ~/pdb/mmCIF/th/3tho.cif.gz cif
cp ~/pdb/mmCIF/th/3thw.cif.gz cif
cp ~/pdb/mmCIF/th/3thx.cif.gz cif
cp ~/pdb/mmCIF/th/3thy.cif.gz cif
cp ~/pdb/mmCIF/th/3thz.cif.gz cif
cp ~/pdb/mmCIF/ti/3tiv.cif.gz cif
cp ~/pdb/mmCIF/tu/3tui.cif.gz cif
cp ~/pdb/mmCIF/tu/3tuj.cif.gz cif
cp ~/pdb/mmCIF/tu/3tul.cif.gz cif
cp ~/pdb/mmCIF/tu/3tuz.cif.gz cif
cp ~/pdb/mmCIF/u0/3u0c.cif.gz cif
cp ~/pdb/mmCIF/u4/3u44.cif.gz cif
cp ~/pdb/mmCIF/u5/3u5z.cif.gz cif
cp ~/pdb/mmCIF/u8/3u8p.cif.gz cif
cp ~/pdb/mmCIF/u9/3u9j.cif.gz cif
cp ~/pdb/mmCIF/uk/3uk6.cif.gz cif
cp ~/pdb/mmCIF/up/3upu.cif.gz cif
cp ~/pdb/mmCIF/uw/3uwx.cif.gz cif
cp ~/pdb/mmCIF/ux/3ux8.cif.gz cif
cp ~/pdb/mmCIF/va/3va9.cif.gz cif
cp ~/pdb/mmCIF/vk/3vkw.cif.gz cif
cp ~/pdb/mmCIF/vr/3vr2.cif.gz cif
cp ~/pdb/mmCIF/vr/3vr3.cif.gz cif
cp ~/pdb/mmCIF/vr/3vr4.cif.gz cif
cp ~/pdb/mmCIF/vr/3vr5.cif.gz cif
cp ~/pdb/mmCIF/vr/3vr6.cif.gz cif
cp ~/pdb/mmCIF/vu/3vu9.cif.gz cif
cp ~/pdb/mmCIF/vx/3vx4.cif.gz cif
cp ~/pdb/mmCIF/wa/3waq.cif.gz cif
cp ~/pdb/mmCIF/wf/3wfv.cif.gz cif
cp ~/pdb/mmCIF/wh/3whj.cif.gz cif
cp ~/pdb/mmCIF/wm/3wme.cif.gz cif
cp ~/pdb/mmCIF/wm/3wmf.cif.gz cif
cp ~/pdb/mmCIF/wm/3wmg.cif.gz cif
cp ~/pdb/mmCIF/zd/3zdq.cif.gz cif
cp ~/pdb/mmCIF/ze/3ze5.cif.gz cif
cp ~/pdb/mmCIF/zg/3zgx.cif.gz cif
cp ~/pdb/mmCIF/zh/3zh9.cif.gz cif
cp ~/pdb/mmCIF/zi/3zia.cif.gz cif
cp ~/pdb/mmCIF/zl/3zlj.cif.gz cif
cp ~/pdb/mmCIF/zq/3zqj.cif.gz cif
cp ~/pdb/mmCIF/zr/3zry.cif.gz cif
cp ~/pdb/mmCIF/zt/3zth.cif.gz cif
cp ~/pdb/mmCIF/zu/3zuh.cif.gz cif
cp ~/pdb/mmCIF/zx/3zx6.cif.gz cif
cp ~/pdb/mmCIF/a1/4a15.cif.gz cif
cp ~/pdb/mmCIF/a1/4a1f.cif.gz cif
cp ~/pdb/mmCIF/a6/4a6p.cif.gz cif
cp ~/pdb/mmCIF/a6/4a6x.cif.gz cif
cp ~/pdb/mmCIF/a8/4a82.cif.gz cif
cp ~/pdb/mmCIF/a8/4a8j.cif.gz cif
cp ~/pdb/mmCIF/ab/4aby.cif.gz cif
cp ~/pdb/mmCIF/ac/4ac8.cif.gz cif
cp ~/pdb/mmCIF/ad/4ad8.cif.gz cif
cp ~/pdb/mmCIF/af/4afl.cif.gz cif
cp ~/pdb/mmCIF/ag/4ag5.cif.gz cif
cp ~/pdb/mmCIF/ag/4ag6.cif.gz cif
cp ~/pdb/mmCIF/ai/4ai6.cif.gz cif
cp ~/pdb/mmCIF/ak/4akk.cif.gz cif
cp ~/pdb/mmCIF/as/4asu.cif.gz cif
cp ~/pdb/mmCIF/av/4avm.cif.gz cif
cp ~/pdb/mmCIF/ay/4ayt.cif.gz cif
cp ~/pdb/mmCIF/ay/4ayw.cif.gz cif
cp ~/pdb/mmCIF/ay/4ayx.cif.gz cif
cp ~/pdb/mmCIF/b2/4b2i.cif.gz cif
cp ~/pdb/mmCIF/b2/4b2l.cif.gz cif
cp ~/pdb/mmCIF/b2/4b2p.cif.gz cif
cp ~/pdb/mmCIF/b2/4b2q.cif.gz cif
cp ~/pdb/mmCIF/b3/4b32.cif.gz cif
cp ~/pdb/mmCIF/b3/4b33.cif.gz cif
cp ~/pdb/mmCIF/b3/4b34.cif.gz cif
cp ~/pdb/mmCIF/b3/4b35.cif.gz cif
cp ~/pdb/mmCIF/b3/4b3b.cif.gz cif
cp ~/pdb/mmCIF/b3/4b3c.cif.gz cif
cp ~/pdb/mmCIF/b3/4b3d.cif.gz cif
cp ~/pdb/mmCIF/b6/4b6x.cif.gz cif
cp ~/pdb/mmCIF/bi/4bil.cif.gz cif
cp ~/pdb/mmCIF/bj/4bj6.cif.gz cif
cp ~/pdb/mmCIF/bl/4blo.cif.gz cif
cp ~/pdb/mmCIF/bl/4blp.cif.gz cif
cp ~/pdb/mmCIF/bl/4blt.cif.gz cif
cp ~/pdb/mmCIF/bw/4bwy.cif.gz cif
cp ~/pdb/mmCIF/c3/4c3z.cif.gz cif
cp ~/pdb/mmCIF/ce/4cej.cif.gz cif
cp ~/pdb/mmCIF/cg/4cgz.cif.gz cif
cp ~/pdb/mmCIF/cr/4crm.cif.gz cif
cp ~/pdb/mmCIF/d2/4d2i.cif.gz cif
cp ~/pdb/mmCIF/d6/4d6p.cif.gz cif
cp ~/pdb/mmCIF/d8/4d80.cif.gz cif
cp ~/pdb/mmCIF/db/4dbl.cif.gz cif
cp ~/pdb/mmCIF/dc/4dc9.cif.gz cif
cp ~/pdb/mmCIF/dd/4ddt.cif.gz cif
cp ~/pdb/mmCIF/dt/4dt1.cif.gz cif
cp ~/pdb/mmCIF/du/4dug.cif.gz cif
cp ~/pdb/mmCIF/dy/4dyl.cif.gz cif
cp ~/pdb/mmCIF/ej/4ejs.cif.gz cif
cp ~/pdb/mmCIF/es/4esv.cif.gz cif
cp ~/pdb/mmCIF/f4/4f4c.cif.gz cif
cp ~/pdb/mmCIF/f9/4f91.cif.gz cif
cp ~/pdb/mmCIF/f9/4f92.cif.gz cif
cp ~/pdb/mmCIF/fi/4fi3.cif.gz cif
cp ~/pdb/mmCIF/fi/4fin.cif.gz cif
cp ~/pdb/mmCIF/fw/4fw9.cif.gz cif
cp ~/pdb/mmCIF/fw/4fwi.cif.gz cif
cp ~/pdb/mmCIF/fy/4fyg.cif.gz cif
cp ~/pdb/mmCIF/fz/4fzs.cif.gz cif
cp ~/pdb/mmCIF/g1/4g1u.cif.gz cif
cp ~/pdb/mmCIF/g3/4g3h.cif.gz cif
cp ~/pdb/mmCIF/gd/4gdf.cif.gz cif
cp ~/pdb/mmCIF/h6/4h63.cif.gz cif
cp ~/pdb/mmCIF/hk/4hkr.cif.gz cif
cp ~/pdb/mmCIF/hl/4hlu.cif.gz cif
cp ~/pdb/mmCIF/hu/4huq.cif.gz cif
cp ~/pdb/mmCIF/hu/4hut.cif.gz cif
cp ~/pdb/mmCIF/hy/4hyy.cif.gz cif
cp ~/pdb/mmCIF/hz/4hzi.cif.gz cif
cp ~/pdb/mmCIF/hz/4hzu.cif.gz cif
cp ~/pdb/mmCIF/i9/4i99.cif.gz cif
cp ~/pdb/mmCIF/id/4idh.cif.gz cif
cp ~/pdb/mmCIF/ie/4iee.cif.gz cif
cp ~/pdb/mmCIF/ie/4iei.cif.gz cif
cp ~/pdb/mmCIF/if/4ife.cif.gz cif
cp ~/pdb/mmCIF/ih/4ihq.cif.gz cif
cp ~/pdb/mmCIF/ij/4ijm.cif.gz cif
cp ~/pdb/mmCIF/ir/4ire.cif.gz cif
cp ~/pdb/mmCIF/j4/4j41.cif.gz cif
cp ~/pdb/mmCIF/jb/4jbw.cif.gz cif
cp ~/pdb/mmCIF/jf/4jf3.cif.gz cif
cp ~/pdb/mmCIF/jw/4jw1.cif.gz cif
cp ~/pdb/mmCIF/k0/4k0d.cif.gz cif
cp ~/pdb/mmCIF/k8/4k8o.cif.gz cif
cp ~/pdb/mmCIF/kf/4kfr.cif.gz cif
cp ~/pdb/mmCIF/kf/4kfs.cif.gz cif
cp ~/pdb/mmCIF/kf/4kft.cif.gz cif
cp ~/pdb/mmCIF/kf/4kfu.cif.gz cif
cp ~/pdb/mmCIF/kh/4khz.cif.gz cif
cp ~/pdb/mmCIF/ki/4ki0.cif.gz cif
cp ~/pdb/mmCIF/ks/4ksb.cif.gz cif
cp ~/pdb/mmCIF/ks/4ksc.cif.gz cif
cp ~/pdb/mmCIF/ks/4ksd.cif.gz cif
cp ~/pdb/mmCIF/ks/4ksr.cif.gz cif
cp ~/pdb/mmCIF/kx/4kxr.cif.gz cif
cp ~/pdb/mmCIF/l0/4l0r.cif.gz cif
cp ~/pdb/mmCIF/l4/4l4u.cif.gz cif
cp ~/pdb/mmCIF/lg/4lgm.cif.gz cif
cp ~/pdb/mmCIF/lw/4lws.cif.gz cif
cp ~/pdb/mmCIF/ly/4lya.cif.gz cif
cp ~/pdb/mmCIF/m1/4m1m.cif.gz cif
cp ~/pdb/mmCIF/m2/4m2s.cif.gz cif
cp ~/pdb/mmCIF/m2/4m2t.cif.gz cif
cp ~/pdb/mmCIF/m4/4m4w.cif.gz cif
cp ~/pdb/mmCIF/m9/4m9s.cif.gz cif
cp ~/pdb/mmCIF/mk/4mki.cif.gz cif
cp ~/pdb/mmCIF/mr/4mrn.cif.gz cif
cp ~/pdb/mmCIF/mr/4mrp.cif.gz cif
cp ~/pdb/mmCIF/mr/4mrr.cif.gz cif
cp ~/pdb/mmCIF/mr/4mrs.cif.gz cif
cp ~/pdb/mmCIF/mr/4mrv.cif.gz cif
cp ~/pdb/mmCIF/my/4myc.cif.gz cif
cp ~/pdb/mmCIF/my/4myh.cif.gz cif
cp ~/pdb/mmCIF/n1/4n1a.cif.gz cif
cp ~/pdb/mmCIF/nb/4nb5.cif.gz cif
cp ~/pdb/mmCIF/nc/4nch.cif.gz cif
cp ~/pdb/mmCIF/nc/4nci.cif.gz cif
cp ~/pdb/mmCIF/nc/4ncj.cif.gz cif
cp ~/pdb/mmCIF/nc/4nck.cif.gz cif
cp ~/pdb/mmCIF/nh/4nh0.cif.gz cif
cp ~/pdb/mmCIF/nl/4nl4.cif.gz cif
cp ~/pdb/mmCIF/nl/4nl8.cif.gz cif
cp ~/pdb/mmCIF/nm/4nmn.cif.gz cif
cp ~/pdb/mmCIF/np/4nph.cif.gz cif
cp ~/pdb/mmCIF/ns/4nsm.cif.gz cif
cp ~/pdb/mmCIF/o0/4o0m.cif.gz cif
cp ~/pdb/mmCIF/o5/4o5j.cif.gz cif
cp ~/pdb/mmCIF/o7/4o7g.cif.gz cif
cp ~/pdb/mmCIF/p3/4p31.cif.gz cif
cp ~/pdb/mmCIF/p3/4p32.cif.gz cif
cp ~/pdb/mmCIF/p3/4p33.cif.gz cif
cp ~/pdb/mmCIF/ph/4pht.cif.gz cif
cp ~/pdb/mmCIF/pi/4pir.cif.gz cif
cp ~/pdb/mmCIF/pl/4pl0.cif.gz cif
cp ~/pdb/mmCIF/pq/4pqy.cif.gz cif
cp ~/pdb/mmCIF/pr/4pr0.cif.gz cif
cp ~/pdb/mmCIF/q4/4q4a.cif.gz cif
cp ~/pdb/mmCIF/q4/4q4h.cif.gz cif
cp ~/pdb/mmCIF/q4/4q4j.cif.gz cif
cp ~/pdb/mmCIF/q4/4q4l.cif.gz cif
cp ~/pdb/mmCIF/q7/4q7k.cif.gz cif
cp ~/pdb/mmCIF/q7/4q7l.cif.gz cif
cp ~/pdb/mmCIF/q7/4q7m.cif.gz cif
cp ~/pdb/mmCIF/q9/4q9h.cif.gz cif
cp ~/pdb/mmCIF/q9/4q9i.cif.gz cif
cp ~/pdb/mmCIF/q9/4q9j.cif.gz cif
cp ~/pdb/mmCIF/q9/4q9k.cif.gz cif
cp ~/pdb/mmCIF/q9/4q9l.cif.gz cif
cp ~/pdb/mmCIF/qc/4qc2.cif.gz cif
cp ~/pdb/mmCIF/qk/4qkq.cif.gz cif
cp ~/pdb/mmCIF/qn/4qn1.cif.gz cif
cp ~/pdb/mmCIF/r2/4r2i.cif.gz cif
cp ~/pdb/mmCIF/r7/4r7y.cif.gz cif
cp ~/pdb/mmCIF/r9/4r9u.cif.gz cif
cp ~/pdb/mmCIF/rf/4rfs.cif.gz cif
cp ~/pdb/mmCIF/rh/4rh7.cif.gz cif
cp ~/pdb/mmCIF/rs/4rsi.cif.gz cif
cp ~/pdb/mmCIF/rs/4rsj.cif.gz cif
cp ~/pdb/mmCIF/rv/4rvc.cif.gz cif
cp ~/pdb/mmCIF/ry/4ry2.cif.gz cif
cp ~/pdb/mmCIF/s0/4s0f.cif.gz cif
cp ~/pdb/mmCIF/tk/4tko.cif.gz cif
cp ~/pdb/mmCIF/tl/4tl6.cif.gz cif
cp ~/pdb/mmCIF/tl/4tl7.cif.gz cif
cp ~/pdb/mmCIF/tl/4tl8.cif.gz cif
cp ~/pdb/mmCIF/tl/4tl9.cif.gz cif
cp ~/pdb/mmCIF/tl/4tla.cif.gz cif
cp ~/pdb/mmCIF/tl/4tlb.cif.gz cif
cp ~/pdb/mmCIF/tl/4tlc.cif.gz cif
cp ~/pdb/mmCIF/tl/4tld.cif.gz cif
cp ~/pdb/mmCIF/tl/4tle.cif.gz cif
cp ~/pdb/mmCIF/tq/4tqu.cif.gz cif
cp ~/pdb/mmCIF/tq/4tqv.cif.gz cif
cp ~/pdb/mmCIF/ts/4tsf.cif.gz cif
cp ~/pdb/mmCIF/tt/4tt3.cif.gz cif
cp ~/pdb/mmCIF/tv/4tvs.cif.gz cif
cp ~/pdb/mmCIF/u0/4u00.cif.gz cif
cp ~/pdb/mmCIF/u0/4u02.cif.gz cif
cp ~/pdb/mmCIF/um/4um2.cif.gz cif
cp ~/pdb/mmCIF/uo/4uos.cif.gz cif
cp ~/pdb/mmCIF/uq/4uqo.cif.gz cif
cp ~/pdb/mmCIF/ux/4ux3.cif.gz cif
cp ~/pdb/mmCIF/ux/4uxj.cif.gz cif
cp ~/pdb/mmCIF/ux/4uxx.cif.gz cif
cp ~/pdb/mmCIF/uy/4uy3.cif.gz cif
cp ~/pdb/mmCIF/w5/4w5w.cif.gz cif
cp ~/pdb/mmCIF/w8/4w8f.cif.gz cif
cp ~/pdb/mmCIF/w9/4w9m.cif.gz cif
cp ~/pdb/mmCIF/wb/4wbs.cif.gz cif
cp ~/pdb/mmCIF/wh/4whe.cif.gz cif
cp ~/pdb/mmCIF/wi/4wia.cif.gz cif
cp ~/pdb/mmCIF/wp/4wpc.cif.gz cif
cp ~/pdb/mmCIF/wp/4wpe.cif.gz cif
cp ~/pdb/mmCIF/wz/4wz6.cif.gz cif
cp ~/pdb/mmCIF/xd/4xd7.cif.gz cif
cp ~/pdb/mmCIF/xg/4xgc.cif.gz cif
cp ~/pdb/mmCIF/xg/4xgu.cif.gz cif
cp ~/pdb/mmCIF/xh/4xh3.cif.gz cif
cp ~/pdb/mmCIF/xi/4xig.cif.gz cif
cp ~/pdb/mmCIF/xo/4xoi.cif.gz cif
cp ~/pdb/mmCIF/xq/4xqk.cif.gz cif
cp ~/pdb/mmCIF/xt/4xtc.cif.gz cif
cp ~/pdb/mmCIF/xv/4xvn.cif.gz cif
cp ~/pdb/mmCIF/xw/4xwk.cif.gz cif
cp ~/pdb/mmCIF/yd/4yds.cif.gz cif
cp ~/pdb/mmCIF/ye/4yer.cif.gz cif
cp ~/pdb/mmCIF/yi/4yix.cif.gz cif
cp ~/pdb/mmCIF/yi/4yiy.cif.gz cif
cp ~/pdb/mmCIF/yj/4yj1.cif.gz cif
cp ~/pdb/mmCIF/ym/4yms.cif.gz cif
cp ~/pdb/mmCIF/ym/4ymt.cif.gz cif
cp ~/pdb/mmCIF/ym/4ymu.cif.gz cif
cp ~/pdb/mmCIF/ym/4ymv.cif.gz cif
cp ~/pdb/mmCIF/ym/4ymw.cif.gz cif
cp ~/pdb/mmCIF/yx/4yxw.cif.gz cif
cp ~/pdb/mmCIF/z1/4z1m.cif.gz cif
cp ~/pdb/mmCIF/zc/4zc0.cif.gz cif
cp ~/pdb/mmCIF/zc/4zcf.cif.gz cif
cp ~/pdb/mmCIF/zi/4zir.cif.gz cif
cp ~/pdb/mmCIF/zn/4znl.cif.gz cif
cp ~/pdb/mmCIF/zu/4zu9.cif.gz cif
cp ~/pdb/mmCIF/zv/4zvc.cif.gz cif
cp ~/pdb/mmCIF/zw/4zwt.cif.gz cif
cp ~/pdb/mmCIF/a6/5a63.cif.gz cif
cp ~/pdb/mmCIF/af/5afq.cif.gz cif
cp ~/pdb/mmCIF/aj/5aj3.cif.gz cif
cp ~/pdb/mmCIF/ak/5akb.cif.gz cif
cp ~/pdb/mmCIF/ak/5akc.cif.gz cif
cp ~/pdb/mmCIF/ak/5akd.cif.gz cif
cp ~/pdb/mmCIF/ao/5aor.cif.gz cif
cp ~/pdb/mmCIF/ar/5ara.cif.gz cif
cp ~/pdb/mmCIF/ar/5are.cif.gz cif
cp ~/pdb/mmCIF/ar/5arh.cif.gz cif
cp ~/pdb/mmCIF/ar/5ari.cif.gz cif
cp ~/pdb/mmCIF/aw/5awf.cif.gz cif
cp ~/pdb/mmCIF/aw/5awg.cif.gz cif
cp ~/pdb/mmCIF/b0/5b0o.cif.gz cif
cp ~/pdb/mmCIF/b5/5b57.cif.gz cif
cp ~/pdb/mmCIF/b5/5b58.cif.gz cif
cp ~/pdb/mmCIF/b7/5b7i.cif.gz cif
cp ~/pdb/mmCIF/bk/5bk4.cif.gz cif
cp ~/pdb/mmCIF/bq/5bq5.cif.gz cif
cp ~/pdb/mmCIF/c1/5c1f.cif.gz cif
cp ~/pdb/mmCIF/c2/5c21.cif.gz cif
cp ~/pdb/mmCIF/c7/5c73.cif.gz cif
cp ~/pdb/mmCIF/c7/5c76.cif.gz cif
cp ~/pdb/mmCIF/c7/5c78.cif.gz cif
cp ~/pdb/mmCIF/cd/5cdf.cif.gz cif
cp ~/pdb/mmCIF/d0/5d0u.cif.gz cif
cp ~/pdb/mmCIF/d3/5d3m.cif.gz cif
cp ~/pdb/mmCIF/d5/5d56.cif.gz cif
cp ~/pdb/mmCIF/d6/5d6a.cif.gz cif
cp ~/pdb/mmCIF/d7/5d7t.cif.gz cif
cp ~/pdb/mmCIF/d8/5d80.cif.gz cif
cp ~/pdb/mmCIF/da/5da9.cif.gz cif
cp ~/pdb/mmCIF/da/5dac.cif.gz cif
cp ~/pdb/mmCIF/dg/5dgx.cif.gz cif
cp ~/pdb/mmCIF/dn/5dn6.cif.gz cif
cp ~/pdb/mmCIF/dn/5dny.cif.gz cif
cp ~/pdb/mmCIF/do/5do7.cif.gz cif
cp ~/pdb/mmCIF/do/5doq.cif.gz cif
cp ~/pdb/mmCIF/e7/5e7p.cif.gz cif
cp ~/pdb/mmCIF/ea/5ean.cif.gz cif
cp ~/pdb/mmCIF/eg/5eg1.cif.gz cif
cp ~/pdb/mmCIF/eu/5eum.cif.gz cif
cp ~/pdb/mmCIF/f3/5f3w.cif.gz cif
cp ~/pdb/mmCIF/f4/5f4h.cif.gz cif
cp ~/pdb/mmCIF/f4/5f4y.cif.gz cif
cp ~/pdb/mmCIF/fi/5fij.cif.gz cif
cp ~/pdb/mmCIF/fi/5fik.cif.gz cif
cp ~/pdb/mmCIF/fi/5fil.cif.gz cif
cp ~/pdb/mmCIF/fl/5fl3.cif.gz cif
cp ~/pdb/mmCIF/fl/5fl7.cif.gz cif
cp ~/pdb/mmCIF/fo/5fos.cif.gz cif
cp ~/pdb/mmCIF/fo/5fot.cif.gz cif
cp ~/pdb/mmCIF/fo/5fou.cif.gz cif
cp ~/pdb/mmCIF/fo/5fov.cif.gz cif
cp ~/pdb/mmCIF/fo/5fow.cif.gz cif
cp ~/pdb/mmCIF/fo/5fox.cif.gz cif
cp ~/pdb/mmCIF/fp/5fpk.cif.gz cif
cp ~/pdb/mmCIF/ft/5ftc.cif.gz cif
cp ~/pdb/mmCIF/ft/5ftn.cif.gz cif
cp ~/pdb/mmCIF/g4/5g4f.cif.gz cif
cp ~/pdb/mmCIF/ga/5gad.cif.gz cif
cp ~/pdb/mmCIF/gk/5gko.cif.gz cif
cp ~/pdb/mmCIF/go/5gox.cif.gz cif
cp ~/pdb/mmCIF/gq/5gq1.cif.gz cif
cp ~/pdb/mmCIF/h1/5h1b.cif.gz cif
cp ~/pdb/mmCIF/h6/5h66.cif.gz cif
cp ~/pdb/mmCIF/h6/5h67.cif.gz cif
cp ~/pdb/mmCIF/h6/5h68.cif.gz cif
cp ~/pdb/mmCIF/h6/5h69.cif.gz cif
cp ~/pdb/mmCIF/ha/5ha6.cif.gz cif
cp ~/pdb/mmCIF/hd/5hd9.cif.gz cif
cp ~/pdb/mmCIF/i6/5i6r.cif.gz cif
cp ~/pdb/mmCIF/ic/5ic0.cif.gz cif
cp ~/pdb/mmCIF/id/5idv.cif.gz cif
cp ~/pdb/mmCIF/ik/5ikn.cif.gz cif
cp ~/pdb/mmCIF/ip/5ip0.cif.gz cif
cp ~/pdb/mmCIF/it/5it5.cif.gz cif
cp ~/pdb/mmCIF/iv/5ivw.cif.gz cif
cp ~/pdb/mmCIF/iz/5izs.cif.gz cif
cp ~/pdb/mmCIF/j0/5j0k.cif.gz cif
cp ~/pdb/mmCIF/j0/5j0l.cif.gz cif
cp ~/pdb/mmCIF/j1/5j10.cif.gz cif
cp ~/pdb/mmCIF/j1/5j1f.cif.gz cif
cp ~/pdb/mmCIF/j1/5j1s.cif.gz cif
cp ~/pdb/mmCIF/j2/5j2l.cif.gz cif
cp ~/pdb/mmCIF/j4/5j45.cif.gz cif
cp ~/pdb/mmCIF/j4/5j4h.cif.gz cif
cp ~/pdb/mmCIF/j4/5j4k.cif.gz cif
cp ~/pdb/mmCIF/j4/5j4l.cif.gz cif
cp ~/pdb/mmCIF/j9/5j9w.cif.gz cif
cp ~/pdb/mmCIF/jd/5jdo.cif.gz cif
cp ~/pdb/mmCIF/je/5jec.cif.gz cif
cp ~/pdb/mmCIF/je/5jed.cif.gz cif
cp ~/pdb/mmCIF/je/5jee.cif.gz cif
cp ~/pdb/mmCIF/jf/5jfg.cif.gz cif
cp ~/pdb/mmCIF/jj/5jji.cif.gz cif
cp ~/pdb/mmCIF/jj/5jjl.cif.gz cif
cp ~/pdb/mmCIF/jp/5jpq.cif.gz cif
cp ~/pdb/mmCIF/jr/5jrj.cif.gz cif
cp ~/pdb/mmCIF/js/5jsz.cif.gz cif
cp ~/pdb/mmCIF/ju/5juy.cif.gz cif
cp ~/pdb/mmCIF/jw/5jwq.cif.gz cif
cp ~/pdb/mmCIF/jz/5jzc.cif.gz cif
cp ~/pdb/mmCIF/k8/5k8l.cif.gz cif
cp ~/pdb/mmCIF/ka/5ka5.cif.gz cif
cp ~/pdb/mmCIF/ka/5ka6.cif.gz cif
cp ~/pdb/mmCIF/kd/5kdd.cif.gz cif
cp ~/pdb/mmCIF/kn/5knc.cif.gz cif
cp ~/pdb/mmCIF/ko/5ko2.cif.gz cif
cp ~/pdb/mmCIF/ko/5koy.cif.gz cif
cp ~/pdb/mmCIF/kp/5kpd.cif.gz cif
cp ~/pdb/mmCIF/kp/5kpi.cif.gz cif
cp ~/pdb/mmCIF/kp/5kpj.cif.gz cif
cp ~/pdb/mmCIF/kz/5kzf.cif.gz cif
cp ~/pdb/mmCIF/l2/5l22.cif.gz cif
cp ~/pdb/mmCIF/l7/5l75.cif.gz cif
cp ~/pdb/mmCIF/l8/5l8v.cif.gz cif
cp ~/pdb/mmCIF/lb/5lb2.cif.gz cif
cp ~/pdb/mmCIF/lb/5lb3.cif.gz cif
cp ~/pdb/mmCIF/lb/5lb4.cif.gz cif
cp ~/pdb/mmCIF/lb/5lbi.cif.gz cif
cp ~/pdb/mmCIF/lc/5lcw.cif.gz cif
cp ~/pdb/mmCIF/ld/5ld2.cif.gz cif
cp ~/pdb/mmCIF/li/5lil.cif.gz cif
cp ~/pdb/mmCIF/lj/5lj6.cif.gz cif
cp ~/pdb/mmCIF/lj/5lj7.cif.gz cif
cp ~/pdb/mmCIF/lj/5lj9.cif.gz cif
cp ~/pdb/mmCIF/lj/5lja.cif.gz cif
cp ~/pdb/mmCIF/lk/5lki.cif.gz cif
cp ~/pdb/mmCIF/lk/5lkm.cif.gz cif
cp ~/pdb/mmCIF/ll/5ll6.cif.gz cif
cp ~/pdb/mmCIF/ln/5ln3.cif.gz cif
cp ~/pdb/mmCIF/lt/5lta.cif.gz cif
cp ~/pdb/mmCIF/lt/5ltk.cif.gz cif
cp ~/pdb/mmCIF/lw/5lw7.cif.gz cif
cp ~/pdb/mmCIF/m7/5m7o.cif.gz cif
cp ~/pdb/mmCIF/mg/5mg8.cif.gz cif
cp ~/pdb/mmCIF/mk/5mkk.cif.gz cif
cp ~/pdb/mmCIF/mn/5mnt.cif.gz cif
cp ~/pdb/mmCIF/mp/5mp9.cif.gz cif
cp ~/pdb/mmCIF/mt/5mto.cif.gz cif
cp ~/pdb/mmCIF/mx/5mx5.cif.gz cif
cp ~/pdb/mmCIF/n5/5n5e.cif.gz cif
cp ~/pdb/mmCIF/n7/5n77.cif.gz cif
cp ~/pdb/mmCIF/n7/5n7r.cif.gz cif
cp ~/pdb/mmCIF/nb/5nbd.cif.gz cif
cp ~/pdb/mmCIF/ne/5nen.cif.gz cif
cp ~/pdb/mmCIF/nf/5nfd.cif.gz cif
cp ~/pdb/mmCIF/ni/5nik.cif.gz cif
cp ~/pdb/mmCIF/ni/5nil.cif.gz cif
cp ~/pdb/mmCIF/nj/5nj3.cif.gz cif
cp ~/pdb/mmCIF/nn/5nnv.cif.gz cif
cp ~/pdb/mmCIF/np/5np7.cif.gz cif
cp ~/pdb/mmCIF/nu/5nug.cif.gz cif
cp ~/pdb/mmCIF/nv/5nvu.cif.gz cif
cp ~/pdb/mmCIF/nw/5nwl.cif.gz cif
cp ~/pdb/mmCIF/o5/5o5o.cif.gz cif
cp ~/pdb/mmCIF/o6/5o6b.cif.gz cif
cp ~/pdb/mmCIF/oc/5och.cif.gz cif
cp ~/pdb/mmCIF/od/5odw.cif.gz cif
cp ~/pdb/mmCIF/oe/5oee.cif.gz cif
cp ~/pdb/mmCIF/of/5ofb.cif.gz cif
cp ~/pdb/mmCIF/of/5ofo.cif.gz cif
cp ~/pdb/mmCIF/of/5ofp.cif.gz cif
cp ~/pdb/mmCIF/of/5ofr.cif.gz cif
cp ~/pdb/mmCIF/oq/5oqm.cif.gz cif
cp ~/pdb/mmCIF/qu/5qub.cif.gz cif
cp ~/pdb/mmCIF/qu/5quc.cif.gz cif
cp ~/pdb/mmCIF/qu/5qud.cif.gz cif
cp ~/pdb/mmCIF/qu/5que.cif.gz cif
cp ~/pdb/mmCIF/qu/5quf.cif.gz cif
cp ~/pdb/mmCIF/qu/5qug.cif.gz cif
cp ~/pdb/mmCIF/qu/5quh.cif.gz cif
cp ~/pdb/mmCIF/qu/5qui.cif.gz cif
cp ~/pdb/mmCIF/qu/5quj.cif.gz cif
cp ~/pdb/mmCIF/qu/5quk.cif.gz cif
cp ~/pdb/mmCIF/qu/5qul.cif.gz cif
cp ~/pdb/mmCIF/qu/5qum.cif.gz cif
cp ~/pdb/mmCIF/qu/5qun.cif.gz cif
cp ~/pdb/mmCIF/qu/5quo.cif.gz cif
cp ~/pdb/mmCIF/qu/5qup.cif.gz cif
cp ~/pdb/mmCIF/qu/5quq.cif.gz cif
cp ~/pdb/mmCIF/qu/5qur.cif.gz cif
cp ~/pdb/mmCIF/qu/5qus.cif.gz cif
cp ~/pdb/mmCIF/qu/5qut.cif.gz cif
cp ~/pdb/mmCIF/qu/5quu.cif.gz cif
cp ~/pdb/mmCIF/sw/5sw8.cif.gz cif
cp ~/pdb/mmCIF/sx/5sxa.cif.gz cif
cp ~/pdb/mmCIF/sx/5sxb.cif.gz cif
cp ~/pdb/mmCIF/sx/5sxf.cif.gz cif
cp ~/pdb/mmCIF/sx/5sxi.cif.gz cif
cp ~/pdb/mmCIF/sx/5sxj.cif.gz cif
cp ~/pdb/mmCIF/sz/5szg.cif.gz cif
cp ~/pdb/mmCIF/sz/5szj.cif.gz cif
cp ~/pdb/mmCIF/t4/5t4o.cif.gz cif
cp ~/pdb/mmCIF/tf/5tf7.cif.gz cif
cp ~/pdb/mmCIF/tf/5tf8.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfa.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfb.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfc.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfd.cif.gz cif
cp ~/pdb/mmCIF/tf/5tff.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfg.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfi.cif.gz cif
cp ~/pdb/mmCIF/tf/5tfj.cif.gz cif
cp ~/pdb/mmCIF/tg/5tgw.cif.gz cif
cp ~/pdb/mmCIF/ti/5tin.cif.gz cif
cp ~/pdb/mmCIF/tq/5tqy.cif.gz cif
cp ~/pdb/mmCIF/ts/5tsh.cif.gz cif
cp ~/pdb/mmCIF/ts/5tsi.cif.gz cif
cp ~/pdb/mmCIF/tt/5ttp.cif.gz cif
cp ~/pdb/mmCIF/tv/5tv4.cif.gz cif
cp ~/pdb/mmCIF/tw/5twv.cif.gz cif
cp ~/pdb/mmCIF/u0/5u0s.cif.gz cif
cp ~/pdb/mmCIF/u1/5u1d.cif.gz cif
cp ~/pdb/mmCIF/u7/5u71.cif.gz cif
cp ~/pdb/mmCIF/ua/5uak.cif.gz cif
cp ~/pdb/mmCIF/ua/5uar.cif.gz cif
cp ~/pdb/mmCIF/ud/5udb.cif.gz cif
cp ~/pdb/mmCIF/uj/5uj7.cif.gz cif
cp ~/pdb/mmCIF/uj/5uj9.cif.gz cif
cp ~/pdb/mmCIF/uj/5uja.cif.gz cif
cp ~/pdb/mmCIF/ul/5ulb.cif.gz cif
cp ~/pdb/mmCIF/v5/5v5s.cif.gz cif
cp ~/pdb/mmCIF/v6/5v6p.cif.gz cif
cp ~/pdb/mmCIF/v8/5v8f.cif.gz cif
cp ~/pdb/mmCIF/vc/5vc7.cif.gz cif
cp ~/pdb/mmCIF/vc/5vca.cif.gz cif
cp ~/pdb/mmCIF/vh/5vhx.cif.gz cif
cp ~/pdb/mmCIF/vl/5vlr.cif.gz cif
cp ~/pdb/mmCIF/vo/5vox.cif.gz cif
cp ~/pdb/mmCIF/vq/5vqa.cif.gz cif
cp ~/pdb/mmCIF/vy/5vyk.cif.gz cif
cp ~/pdb/mmCIF/w0/5w0t.cif.gz cif
cp ~/pdb/mmCIF/w8/5w81.cif.gz cif
cp ~/pdb/mmCIF/ws/5ws4.cif.gz cif
cp ~/pdb/mmCIF/wu/5wua.cif.gz cif
cp ~/pdb/mmCIF/ww/5wwp.cif.gz cif
cp ~/pdb/mmCIF/x3/5x3x.cif.gz cif
cp ~/pdb/mmCIF/x4/5x40.cif.gz cif
cp ~/pdb/mmCIF/x4/5x41.cif.gz cif
cp ~/pdb/mmCIF/x5/5x5y.cif.gz cif
cp ~/pdb/mmCIF/x6/5x6o.cif.gz cif
cp ~/pdb/mmCIF/x7/5x71.cif.gz cif
cp ~/pdb/mmCIF/x7/5x7k.cif.gz cif
cp ~/pdb/mmCIF/x9/5x9w.cif.gz cif
cp ~/pdb/mmCIF/xa/5xa5.cif.gz cif
cp ~/pdb/mmCIF/xb/5xbj.cif.gz cif
cp ~/pdb/mmCIF/xe/5xei.cif.gz cif
cp ~/pdb/mmCIF/xf/5xfs.cif.gz cif
cp ~/pdb/mmCIF/xg/5xg2.cif.gz cif
cp ~/pdb/mmCIF/xg/5xg3.cif.gz cif
cp ~/pdb/mmCIF/xj/5xjy.cif.gz cif
cp ~/pdb/mmCIF/xm/5xmi.cif.gz cif
cp ~/pdb/mmCIF/xn/5xns.cif.gz cif
cp ~/pdb/mmCIF/xq/5xqi.cif.gz cif
cp ~/pdb/mmCIF/xs/5xsj.cif.gz cif
cp ~/pdb/mmCIF/xu/5xu0.cif.gz cif
cp ~/pdb/mmCIF/xu/5xu1.cif.gz cif
cp ~/pdb/mmCIF/xu/5xua.cif.gz cif
cp ~/pdb/mmCIF/xy/5xyn.cif.gz cif
cp ~/pdb/mmCIF/y0/5y05.cif.gz cif
cp ~/pdb/mmCIF/y0/5y06.cif.gz cif
cp ~/pdb/mmCIF/y5/5y5y.cif.gz cif
cp ~/pdb/mmCIF/yi/5yim.cif.gz cif
cp ~/pdb/mmCIF/yk/5yk4.cif.gz cif
cp ~/pdb/mmCIF/yk/5yke.cif.gz cif
cp ~/pdb/mmCIF/yk/5ykf.cif.gz cif
cp ~/pdb/mmCIF/yk/5ykg.cif.gz cif
cp ~/pdb/mmCIF/yu/5yud.cif.gz cif
cp ~/pdb/mmCIF/yv/5yv5.cif.gz cif
cp ~/pdb/mmCIF/yv/5yvu.cif.gz cif
cp ~/pdb/mmCIF/yw/5yw7.cif.gz cif
cp ~/pdb/mmCIF/yw/5yw8.cif.gz cif
cp ~/pdb/mmCIF/yw/5yw9.cif.gz cif
cp ~/pdb/mmCIF/yw/5ywa.cif.gz cif
cp ~/pdb/mmCIF/yw/5ywb.cif.gz cif
cp ~/pdb/mmCIF/yw/5ywc.cif.gz cif
cp ~/pdb/mmCIF/yw/5ywd.cif.gz cif
cp ~/pdb/mmCIF/yw/5yww.cif.gz cif
cp ~/pdb/mmCIF/yz/5yz8.cif.gz cif
cp ~/pdb/mmCIF/z5/5z51.cif.gz cif
cp ~/pdb/mmCIF/z6/5z67.cif.gz cif
cp ~/pdb/mmCIF/z6/5z68.cif.gz cif
cp ~/pdb/mmCIF/z6/5z69.cif.gz cif
cp ~/pdb/mmCIF/zh/5zhy.cif.gz cif
cp ~/pdb/mmCIF/zr/5zr1.cif.gz cif
cp ~/pdb/mmCIF/zw/5zwu.cif.gz cif
cp ~/pdb/mmCIF/zx/5zxd.cif.gz cif
cp ~/pdb/mmCIF/a6/6a6m.cif.gz cif
cp ~/pdb/mmCIF/a6/6a6n.cif.gz cif
cp ~/pdb/mmCIF/ac/6acx.cif.gz cif
cp ~/pdb/mmCIF/ah/6ah0.cif.gz cif
cp ~/pdb/mmCIF/an/6an5.cif.gz cif
cp ~/pdb/mmCIF/an/6an7.cif.gz cif
cp ~/pdb/mmCIF/b8/6b87.cif.gz cif
cp ~/pdb/mmCIF/b8/6b89.cif.gz cif
cp ~/pdb/mmCIF/b8/6b8b.cif.gz cif
cp ~/pdb/mmCIF/ba/6baa.cif.gz cif
cp ~/pdb/mmCIF/bb/6bbm.cif.gz cif
cp ~/pdb/mmCIF/bh/6bhu.cif.gz cif
cp ~/pdb/mmCIF/bl/6bl6.cif.gz cif
cp ~/pdb/mmCIF/bo/6bog.cif.gz cif
cp ~/pdb/mmCIF/bp/6bpl.cif.gz cif
cp ~/pdb/mmCIF/bp/6bpp.cif.gz cif
cp ~/pdb/mmCIF/bt/6btm.cif.gz cif
cp ~/pdb/mmCIF/bu/6bua.cif.gz cif
cp ~/pdb/mmCIF/bz/6bzr.cif.gz cif
cp ~/pdb/mmCIF/bz/6bzs.cif.gz cif
cp ~/pdb/mmCIF/c0/6c0v.cif.gz cif
cp ~/pdb/mmCIF/c3/6c3o.cif.gz cif
cp ~/pdb/mmCIF/c3/6c3p.cif.gz cif
cp ~/pdb/mmCIF/cn/6cnm.cif.gz cif
cp ~/pdb/mmCIF/cs/6csv.cif.gz cif
cp ~/pdb/mmCIF/cv/6cvl.cif.gz cif
cp ~/pdb/mmCIF/d0/6d03.cif.gz cif
cp ~/pdb/mmCIF/d3/6d3r.cif.gz cif
cp ~/pdb/mmCIF/d3/6d3s.cif.gz cif
cp ~/pdb/mmCIF/dg/6dgd.cif.gz cif
cp ~/pdb/mmCIF/dj/6djl.cif.gz cif
cp ~/pdb/mmCIF/dl/6dlm.cif.gz cif
cp ~/pdb/mmCIF/dm/6dma.cif.gz cif
cp ~/pdb/mmCIF/e7/6e7e.cif.gz cif
cp ~/pdb/mmCIF/ee/6ees.cif.gz cif
cp ~/pdb/mmCIF/ej/6ejq.cif.gz cif
cp ~/pdb/mmCIF/ek/6ek4.cif.gz cif
cp ~/pdb/mmCIF/ek/6ek7.cif.gz cif
cp ~/pdb/mmCIF/el/6el1.cif.gz cif
cp ~/pdb/mmCIF/ep/6epc.cif.gz cif
cp ~/pdb/mmCIF/et/6eti.cif.gz cif
cp ~/pdb/mmCIF/et/6etx.cif.gz cif
cp ~/pdb/mmCIF/eu/6eud.cif.gz cif
cp ~/pdb/mmCIF/ew/6ewy.cif.gz cif
cp ~/pdb/mmCIF/ey/6eyd.cif.gz cif
cp ~/pdb/mmCIF/f0/6f0x.cif.gz cif
cp ~/pdb/mmCIF/fe/6feq.cif.gz cif
cp ~/pdb/mmCIF/ff/6ffc.cif.gz cif
cp ~/pdb/mmCIF/fh/6fhs.cif.gz cif
cp ~/pdb/mmCIF/fl/6flx.cif.gz cif
cp ~/pdb/mmCIF/fn/6fn1.cif.gz cif
cp ~/pdb/mmCIF/fn/6fn4.cif.gz cif
cp ~/pdb/mmCIF/fn/6fnp.cif.gz cif
cp ~/pdb/mmCIF/fp/6fpf.cif.gz cif
cp ~/pdb/mmCIF/fw/6fws.cif.gz cif
cp ~/pdb/mmCIF/gd/6gdi.cif.gz cif
cp ~/pdb/mmCIF/ge/6gef.cif.gz cif
cp ~/pdb/mmCIF/ge/6gej.cif.gz cif
cp ~/pdb/mmCIF/gj/6gjq.cif.gz cif
cp ~/pdb/mmCIF/gj/6gjs.cif.gz cif
cp ~/pdb/mmCIF/gj/6gju.cif.gz cif
cp ~/pdb/mmCIF/gk/6gk4.cif.gz cif
cp ~/pdb/mmCIF/gk/6gkd.cif.gz cif
cp ~/pdb/mmCIF/h3/6h3z.cif.gz cif
cp ~/pdb/mmCIF/hb/6hbu.cif.gz cif
cp ~/pdb/mmCIF/hi/6hij.cif.gz cif
cp ~/pdb/mmCIF/hk/6hk5.cif.gz cif
cp ~/pdb/mmCIF/hq/6hqu.cif.gz cif
cp ~/pdb/mmCIF/hr/6hrc.cif.gz cif
cp ~/pdb/mmCIF/hs/6hs3.cif.gz cif
cp ~/pdb/mmCIF/hy/6hyp.cif.gz cif
cp ~/pdb/mmCIF/hz/6hz4.cif.gz cif
cp ~/pdb/mmCIF/hz/6hz7.cif.gz cif
cp ~/pdb/mmCIF/hz/6hz8.cif.gz cif
cp ~/pdb/mmCIF/hz/6hz9.cif.gz cif
cp ~/pdb/mmCIF/hz/6hzm.cif.gz cif
cp ~/pdb/mmCIF/i5/6i5f.cif.gz cif
cp ~/pdb/mmCIF/ic/6ic4.cif.gz cif
cp ~/pdb/mmCIF/ik/6ikn.cif.gz cif
cp ~/pdb/mmCIF/ik/6iko.cif.gz cif
cp ~/pdb/mmCIF/ix/6ixv.cif.gz cif
cp ~/pdb/mmCIF/iy/6iy8.cif.gz cif
cp ~/pdb/mmCIF/j1/6j17.cif.gz cif
cp ~/pdb/mmCIF/j1/6j18.cif.gz cif
cp ~/pdb/mmCIF/j5/6j5t.cif.gz cif
cp ~/pdb/mmCIF/j6/6j6i.cif.gz cif
cp ~/pdb/mmCIF/j7/6j72.cif.gz cif
cp ~/pdb/mmCIF/jb/6jb1.cif.gz cif
cp ~/pdb/mmCIF/jb/6jb3.cif.gz cif
cp ~/pdb/mmCIF/jb/6jbj.cif.gz cif
cp ~/pdb/mmCIF/jd/6jd5.cif.gz cif
cp ~/pdb/mmCIF/ji/6jim.cif.gz cif
cp ~/pdb/mmCIF/jp/6jpq.cif.gz cif
cp ~/pdb/mmCIF/jq/6jqa.cif.gz cif
cp ~/pdb/mmCIF/k9/6k9c.cif.gz cif
cp ~/pdb/mmCIF/l1/6l1q.cif.gz cif
cp ~/pdb/mmCIF/lq/6lqo.cif.gz cif
cp ~/pdb/mmCIF/lu/6lum.cif.gz cif
cp ~/pdb/mmCIF/m4/6m40.cif.gz cif
cp ~/pdb/mmCIF/m9/6m96.cif.gz cif
cp ~/pdb/mmCIF/ma/6mat.cif.gz cif
cp ~/pdb/mmCIF/mb/6mbn.cif.gz cif
cp ~/pdb/mmCIF/md/6mdm.cif.gz cif
cp ~/pdb/mmCIF/mf/6mfv.cif.gz cif
cp ~/pdb/mmCIF/mg/6mgf.cif.gz cif
cp ~/pdb/mmCIF/mh/6mhu.cif.gz cif
cp ~/pdb/mmCIF/mh/6mhz.cif.gz cif
cp ~/pdb/mmCIF/mi/6mi7.cif.gz cif
cp ~/pdb/mmCIF/mi/6mi8.cif.gz cif
cp ~/pdb/mmCIF/mi/6mit.cif.gz cif
cp ~/pdb/mmCIF/mj/6mjp.cif.gz cif
cp ~/pdb/mmCIF/mr/6mru.cif.gz cif
cp ~/pdb/mmCIF/ms/6msm.cif.gz cif
cp ~/pdb/mmCIF/my/6myo.cif.gz cif
cp ~/pdb/mmCIF/n7/6n7i.cif.gz cif
cp ~/pdb/mmCIF/n7/6n7n.cif.gz cif
cp ~/pdb/mmCIF/n7/6n7s.cif.gz cif
cp ~/pdb/mmCIF/n7/6n7t.cif.gz cif
cp ~/pdb/mmCIF/n7/6n7v.cif.gz cif
cp ~/pdb/mmCIF/n9/6n9l.cif.gz cif
cp ~/pdb/mmCIF/n9/6n9v.cif.gz cif
cp ~/pdb/mmCIF/n9/6n9w.cif.gz cif
cp ~/pdb/mmCIF/n9/6n9x.cif.gz cif
cp ~/pdb/mmCIF/nc/6nct.cif.gz cif
cp ~/pdb/mmCIF/ne/6neq.cif.gz cif
cp ~/pdb/mmCIF/nl/6nlo.cif.gz cif
cp ~/pdb/mmCIF/nm/6nmi.cif.gz cif
cp ~/pdb/mmCIF/np/6npy.cif.gz cif
cp ~/pdb/mmCIF/nq/6nq8.cif.gz cif
cp ~/pdb/mmCIF/nr/6nr8.cif.gz cif
cp ~/pdb/mmCIF/nr/6nr9.cif.gz cif
cp ~/pdb/mmCIF/nr/6nrb.cif.gz cif
cp ~/pdb/mmCIF/nr/6nrc.cif.gz cif
cp ~/pdb/mmCIF/nr/6nrd.cif.gz cif
cp ~/pdb/mmCIF/ny/6nye.cif.gz cif
cp ~/pdb/mmCIF/ny/6nyy.cif.gz cif
cp ~/pdb/mmCIF/nz/6nz3.cif.gz cif
cp ~/pdb/mmCIF/o1/6o16.cif.gz cif
cp ~/pdb/mmCIF/o1/6o1v.cif.gz cif
cp ~/pdb/mmCIF/o2/6o2p.cif.gz cif
cp ~/pdb/mmCIF/o3/6o35.cif.gz cif
cp ~/pdb/mmCIF/o7/6o7v.cif.gz cif
cp ~/pdb/mmCIF/o7/6o7w.cif.gz cif
cp ~/pdb/mmCIF/o7/6o7x.cif.gz cif
cp ~/pdb/mmCIF/oa/6oa9.cif.gz cif
cp ~/pdb/mmCIF/oa/6oaa.cif.gz cif
cp ~/pdb/mmCIF/oa/6oab.cif.gz cif
cp ~/pdb/mmCIF/oa/6oax.cif.gz cif
cp ~/pdb/mmCIF/of/6of2.cif.gz cif
cp ~/pdb/mmCIF/oi/6ois.cif.gz cif
cp ~/pdb/mmCIF/oj/6ojy.cif.gz cif
cp ~/pdb/mmCIF/op/6opc.cif.gz cif
cp ~/pdb/mmCIF/oq/6oqr.cif.gz cif
cp ~/pdb/mmCIF/oq/6oqs.cif.gz cif
cp ~/pdb/mmCIF/oq/6oqt.cif.gz cif
cp ~/pdb/mmCIF/oq/6oqu.cif.gz cif
cp ~/pdb/mmCIF/oq/6oqv.cif.gz cif
cp ~/pdb/mmCIF/or/6orb.cif.gz cif
cp ~/pdb/mmCIF/p0/6p07.cif.gz cif
cp ~/pdb/mmCIF/p6/6p6i.cif.gz cif
cp ~/pdb/mmCIF/p6/6p6j.cif.gz cif
cp ~/pdb/mmCIF/p7/6p74.cif.gz cif
cp ~/pdb/mmCIF/p7/6p7f.cif.gz cif
cp ~/pdb/mmCIF/p8/6p8v.cif.gz cif
cp ~/pdb/mmCIF/pa/6pam.cif.gz cif
cp ~/pdb/mmCIF/pa/6pan.cif.gz cif
cp ~/pdb/mmCIF/pa/6pao.cif.gz cif
cp ~/pdb/mmCIF/pa/6paq.cif.gz cif
cp ~/pdb/mmCIF/pa/6par.cif.gz cif
cp ~/pdb/mmCIF/pb/6pb3.cif.gz cif
cp ~/pdb/mmCIF/pd/6pdy.cif.gz cif
cp ~/pdb/mmCIF/pe/6pe4.cif.gz cif
cp ~/pdb/mmCIF/pf/6pfv.cif.gz cif
cp ~/pdb/mmCIF/pp/6ppj.cif.gz cif
cp ~/pdb/mmCIF/pq/6pqv.cif.gz cif
cp ~/pdb/mmCIF/px/6pxk.cif.gz cif
cp ~/pdb/mmCIF/pz/6pz9.cif.gz cif
cp ~/pdb/mmCIF/pz/6pza.cif.gz cif
cp ~/pdb/mmCIF/pz/6pzb.cif.gz cif
cp ~/pdb/mmCIF/pz/6pzc.cif.gz cif
cp ~/pdb/mmCIF/pz/6pzi.cif.gz cif
cp ~/pdb/mmCIF/q8/6q81.cif.gz cif
cp ~/pdb/mmCIF/qe/6qee.cif.gz cif
cp ~/pdb/mmCIF/qe/6qel.cif.gz cif
cp ~/pdb/mmCIF/qe/6qem.cif.gz cif
cp ~/pdb/mmCIF/qe/6qex.cif.gz cif
cp ~/pdb/mmCIF/qi/6qi8.cif.gz cif
cp ~/pdb/mmCIF/qj/6qj0.cif.gz cif
cp ~/pdb/mmCIF/qj/6qj1.cif.gz cif
cp ~/pdb/mmCIF/qj/6qj2.cif.gz cif
cp ~/pdb/mmCIF/qj/6qj4.cif.gz cif
cp ~/pdb/mmCIF/qp/6qpq.cif.gz cif
cp ~/pdb/mmCIF/qp/6qpw.cif.gz cif
cp ~/pdb/mmCIF/qu/6qum.cif.gz cif
cp ~/pdb/mmCIF/qu/6quz.cif.gz cif
cp ~/pdb/mmCIF/qv/6qv0.cif.gz cif
cp ~/pdb/mmCIF/qv/6qv1.cif.gz cif
cp ~/pdb/mmCIF/qv/6qv2.cif.gz cif
cp ~/pdb/mmCIF/r0/6r0z.cif.gz cif
cp ~/pdb/mmCIF/r2/6r2g.cif.gz cif
cp ~/pdb/mmCIF/r3/6r3p.cif.gz cif
cp ~/pdb/mmCIF/r7/6r72.cif.gz cif
cp ~/pdb/mmCIF/r8/6r81.cif.gz cif
cp ~/pdb/mmCIF/ra/6raf.cif.gz cif
cp ~/pdb/mmCIF/ra/6rag.cif.gz cif
cp ~/pdb/mmCIF/ra/6rah.cif.gz cif
cp ~/pdb/mmCIF/ra/6rai.cif.gz cif
cp ~/pdb/mmCIF/ra/6raj.cif.gz cif
cp ~/pdb/mmCIF/ra/6rak.cif.gz cif
cp ~/pdb/mmCIF/ra/6ral.cif.gz cif
cp ~/pdb/mmCIF/ra/6ram.cif.gz cif
cp ~/pdb/mmCIF/ra/6ran.cif.gz cif
cp ~/pdb/mmCIF/rd/6rd4.cif.gz cif
cp ~/pdb/mmCIF/re/6ree.cif.gz cif
cp ~/pdb/mmCIF/re/6ref.cif.gz cif
cp ~/pdb/mmCIF/re/6rep.cif.gz cif
cp ~/pdb/mmCIF/re/6rer.cif.gz cif
cp ~/pdb/mmCIF/re/6res.cif.gz cif
cp ~/pdb/mmCIF/re/6ret.cif.gz cif
cp ~/pdb/mmCIF/re/6reu.cif.gz cif
cp ~/pdb/mmCIF/rf/6rfl.cif.gz cif
cp ~/pdb/mmCIF/ri/6ri7.cif.gz cif
cp ~/pdb/mmCIF/rn/6rn3.cif.gz cif
cp ~/pdb/mmCIF/rn/6rn4.cif.gz cif
cp ~/pdb/mmCIF/ro/6ro1.cif.gz cif
cp ~/pdb/mmCIF/s6/6s6v.cif.gz cif
cp ~/pdb/mmCIF/s7/6s7o.cif.gz cif
cp ~/pdb/mmCIF/s7/6s7p.cif.gz cif
cp ~/pdb/mmCIF/s7/6s7t.cif.gz cif
cp ~/pdb/mmCIF/s8/6s85.cif.gz cif
cp ~/pdb/mmCIF/s8/6s8g.cif.gz cif
cp ~/pdb/mmCIF/s8/6s8h.cif.gz cif
cp ~/pdb/mmCIF/s8/6s8n.cif.gz cif
cp ~/pdb/mmCIF/sg/6sgw.cif.gz cif
cp ~/pdb/mmCIF/sg/6sgx.cif.gz cif
cp ~/pdb/mmCIF/sg/6sgz.cif.gz cif
cp ~/pdb/mmCIF/sh/6sh3.cif.gz cif
cp ~/pdb/mmCIF/so/6so5.cif.gz cif
cp ~/pdb/mmCIF/so/6soy.cif.gz cif
cp ~/pdb/mmCIF/sx/6sxa.cif.gz cif
cp ~/pdb/mmCIF/sz/6sz9.cif.gz cif
cp ~/pdb/mmCIF/te/6tej.cif.gz cif
cp ~/pdb/mmCIF/tj/6tj1.cif.gz cif
cp ~/pdb/mmCIF/tm/6tmf.cif.gz cif
cp ~/pdb/mmCIF/tm/6tms.cif.gz cif
cp ~/pdb/mmCIF/tq/6tqe.cif.gz cif
cp ~/pdb/mmCIF/tq/6tqf.cif.gz cif
cp ~/pdb/mmCIF/tu/6tuu.cif.gz cif
cp ~/pdb/mmCIF/tv/6tv1.cif.gz cif
cp ~/pdb/mmCIF/tv/6tv3.cif.gz cif
cp ~/pdb/mmCIF/tw/6tw3.cif.gz cif
cp ~/pdb/mmCIF/tw/6tw4.cif.gz cif
cp ~/pdb/mmCIF/tw/6tw9.cif.gz cif
cp ~/pdb/mmCIF/tx/6txy.cif.gz cif
cp ~/pdb/mmCIF/ty/6ty9.cif.gz cif
cp ~/pdb/mmCIF/u1/6u1y.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujn.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujp.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujr.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujs.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujt.cif.gz cif
cp ~/pdb/mmCIF/uj/6ujw.cif.gz cif
cp ~/pdb/mmCIF/uk/6uks.cif.gz cif
cp ~/pdb/mmCIF/ut/6ut5.cif.gz cif
cp ~/pdb/mmCIF/uu/6uuj.cif.gz cif
cp ~/pdb/mmCIF/uy/6uy0.cif.gz cif
cp ~/pdb/mmCIF/uz/6uz2.cif.gz cif
cp ~/pdb/mmCIF/uz/6uzl.cif.gz cif
cp ~/pdb/mmCIF/v7/6v7m.cif.gz cif
cp ~/pdb/mmCIF/v7/6v7v.cif.gz cif
cp ~/pdb/mmCIF/v9/6v9z.cif.gz cif
cp ~/pdb/mmCIF/vm/6vme.cif.gz cif
cp ~/pdb/mmCIF/vq/6vq6.cif.gz cif
cp ~/pdb/mmCIF/vq/6vq7.cif.gz cif
cp ~/pdb/mmCIF/vq/6vq8.cif.gz cif
cp ~/pdb/mmCIF/vq/6vqc.cif.gz cif
cp ~/pdb/mmCIF/vq/6vqg.cif.gz cif
cp ~/pdb/mmCIF/vq/6vqh.cif.gz cif
cp ~/pdb/mmCIF/vq/6vqt.cif.gz cif
cp ~/pdb/mmCIF/vq/6vqu.cif.gz cif
cp ~/pdb/mmCIF/vv/6vvo.cif.gz cif
cp ~/pdb/mmCIF/vw/6vwk.cif.gz cif
cp ~/pdb/mmCIF/vx/6vxf.cif.gz cif
cp ~/pdb/mmCIF/vx/6vxh.cif.gz cif
cp ~/pdb/mmCIF/vx/6vxi.cif.gz cif
cp ~/pdb/mmCIF/vx/6vxj.cif.gz cif
cp ~/pdb/mmCIF/vy/6vy1.cif.gz cif
cp ~/pdb/mmCIF/w1/6w1s.cif.gz cif
cp ~/pdb/mmCIF/w6/6w6x.cif.gz cif
cp ~/pdb/mmCIF/wa/6wa9.cif.gz cif
cp ~/pdb/mmCIF/wb/6wbs.cif.gz cif
cp ~/pdb/mmCIF/wg/6wg3.cif.gz cif
cp ~/pdb/mmCIF/wg/6wge.cif.gz cif
cp ~/pdb/mmCIF/wn/6wnq.cif.gz cif
cp ~/pdb/mmCIF/wn/6wnr.cif.gz cif
cp ~/pdb/mmCIF/x4/6x44.cif.gz cif
cp ~/pdb/mmCIF/xb/6xbd.cif.gz cif
cp ~/pdb/mmCIF/xb/6xby.cif.gz cif
cp ~/pdb/mmCIF/xg/6xgy.cif.gz cif
cp ~/pdb/mmCIF/xg/6xgz.cif.gz cif
cp ~/pdb/mmCIF/xj/6xjh.cif.gz cif
cp ~/pdb/mmCIF/xj/6xji.cif.gz cif
cp ~/pdb/mmCIF/xt/6xtw.cif.gz cif
cp ~/pdb/mmCIF/xu/6xuf.cif.gz cif
cp ~/pdb/mmCIF/xu/6xuj.cif.gz cif
cp ~/pdb/mmCIF/xz/6xz4.cif.gz cif
cp ~/pdb/mmCIF/ya/6yal.cif.gz cif
cp ~/pdb/mmCIF/yi/6yir.cif.gz cif
cp ~/pdb/mmCIF/yu/6yuf.cif.gz cif
cp ~/pdb/mmCIF/yv/6yvd.cif.gz cif
cp ~/pdb/mmCIF/yv/6yvu.cif.gz cif
cp ~/pdb/mmCIF/yv/6yvv.cif.gz cif
cp ~/pdb/mmCIF/z0/6z0c.cif.gz cif
cp ~/pdb/mmCIF/z1/6z1f.cif.gz cif
cp ~/pdb/mmCIF/z3/6z3w.cif.gz cif
cp ~/pdb/mmCIF/z4/6z4w.cif.gz cif
cp ~/pdb/mmCIF/z5/6z5u.cif.gz cif
cp ~/pdb/mmCIF/z6/6z63.cif.gz cif
cp ~/pdb/mmCIF/z6/6z67.cif.gz cif
cp ~/pdb/mmCIF/z6/6z6d.cif.gz cif
cp ~/pdb/mmCIF/z6/6z6f.cif.gz cif
cp ~/pdb/mmCIF/z7/6z7b.cif.gz cif
cp ~/pdb/mmCIF/zb/6zbc.cif.gz cif
cp ~/pdb/mmCIF/zb/6zbj.cif.gz cif
cp ~/pdb/mmCIF/zc/6zca.cif.gz cif
cp ~/pdb/mmCIF/zc/6zce.cif.gz cif
cp ~/pdb/mmCIF/ze/6ze1.cif.gz cif
cp ~/pdb/mmCIF/zg/6zg3.cif.gz cif
cp ~/pdb/mmCIF/zh/6zh3.cif.gz cif
cp ~/pdb/mmCIF/zs/6zsh.cif.gz cif
cp ~/pdb/mmCIF/zs/6zsi.cif.gz cif
cp ~/pdb/mmCIF/zs/6zsj.cif.gz cif
cp ~/pdb/mmCIF/zu/6zu9.cif.gz cif
cp ~/pdb/mmCIF/zy/6zy2.cif.gz cif
cp ~/pdb/mmCIF/zy/6zy3.cif.gz cif
cp ~/pdb/mmCIF/zy/6zy4.cif.gz cif
cp ~/pdb/mmCIF/zy/6zy9.cif.gz cif
cp ~/pdb/mmCIF/zy/6zyy.cif.gz cif
cp ~/pdb/mmCIF/zz/6zz6.cif.gz cif
cp ~/pdb/mmCIF/a1/7a1g.cif.gz cif
cp ~/pdb/mmCIF/a6/7a65.cif.gz cif
cp ~/pdb/mmCIF/a6/7a69.cif.gz cif
cp ~/pdb/mmCIF/a6/7a6c.cif.gz cif
cp ~/pdb/mmCIF/a6/7a6e.cif.gz cif
cp ~/pdb/mmCIF/a6/7a6f.cif.gz cif
cp ~/pdb/mmCIF/ae/7aej.cif.gz cif
cp ~/pdb/mmCIF/ah/7ahc.cif.gz cif
cp ~/pdb/mmCIF/ah/7ahd.cif.gz cif
cp ~/pdb/mmCIF/ah/7ahe.cif.gz cif
cp ~/pdb/mmCIF/ah/7ahh.cif.gz cif
cp ~/pdb/mmCIF/ai/7ai5.cif.gz cif
cp ~/pdb/mmCIF/ai/7ai6.cif.gz cif
cp ~/pdb/mmCIF/ai/7ai7.cif.gz cif
cp ~/pdb/mmCIF/ai/7aib.cif.gz cif
cp ~/pdb/mmCIF/ai/7aic.cif.gz cif
cp ~/pdb/mmCIF/am/7amv.cif.gz cif
cp ~/pdb/mmCIF/ar/7arh.cif.gz cif
cp ~/pdb/mmCIF/ar/7ari.cif.gz cif
cp ~/pdb/mmCIF/ar/7arj.cif.gz cif
cp ~/pdb/mmCIF/ar/7ark.cif.gz cif
cp ~/pdb/mmCIF/ar/7arl.cif.gz cif
cp ~/pdb/mmCIF/ar/7arm.cif.gz cif
cp ~/pdb/mmCIF/b9/7b9s.cif.gz cif
cp ~/pdb/mmCIF/bc/7bcw.cif.gz cif
cp ~/pdb/mmCIF/bg/7bg4.cif.gz cif
cp ~/pdb/mmCIF/bs/7bst.cif.gz cif
cp ~/pdb/mmCIF/c9/7c98.cif.gz cif
cp ~/pdb/mmCIF/ca/7cad.cif.gz cif
cp ~/pdb/mmCIF/ca/7cae.cif.gz cif
cp ~/pdb/mmCIF/ca/7caf.cif.gz cif
cp ~/pdb/mmCIF/ca/7cag.cif.gz cif
cp ~/pdb/mmCIF/cg/7cge.cif.gz cif
cp ~/pdb/mmCIF/cg/7cgn.cif.gz cif
cp ~/pdb/mmCIF/ch/7ch0.cif.gz cif
cp ~/pdb/mmCIF/ch/7ch6.cif.gz cif
cp ~/pdb/mmCIF/ch/7ch7.cif.gz cif
cp ~/pdb/mmCIF/ch/7ch8.cif.gz cif
cp ~/pdb/mmCIF/ch/7ch9.cif.gz cif
cp ~/pdb/mmCIF/ch/7cha.cif.gz cif
cp ~/pdb/mmCIF/cr/7crc.cif.gz cif
cp ~/pdb/mmCIF/d0/7d06.cif.gz cif
cp ~/pdb/mmCIF/d0/7d09.cif.gz cif
cp ~/pdb/mmCIF/d0/7d0a.cif.gz cif
cp ~/pdb/mmCIF/d3/7d3u.cif.gz cif
cp ~/pdb/mmCIF/d5/7d5i.cif.gz cif
cp ~/pdb/mmCIF/d7/7d76.cif.gz cif
cp ~/pdb/mmCIF/d7/7d7n.cif.gz cif
cp ~/pdb/mmCIF/d7/7d7r.cif.gz cif
cp ~/pdb/mmCIF/dq/7dqv.cif.gz cif
cp ~/pdb/mmCIF/dv/7dv5.cif.gz cif
cp ~/pdb/mmCIF/dy/7dyi.cif.gz cif
cp ~/pdb/mmCIF/dy/7dyk.cif.gz cif
cp ~/pdb/mmCIF/e1/7e1a.cif.gz cif
cp ~/pdb/mmCIF/e1/7e1v.cif.gz cif
cp ~/pdb/mmCIF/e7/7e7i.cif.gz cif
cp ~/pdb/mmCIF/e7/7e7o.cif.gz cif
cp ~/pdb/mmCIF/e7/7e7q.cif.gz cif
cp ~/pdb/mmCIF/ef/7efo.cif.gz cif
cp ~/pdb/mmCIF/eh/7ehl.cif.gz cif
cp ~/pdb/mmCIF/ek/7ekl.cif.gz cif
cp ~/pdb/mmCIF/ek/7ekm.cif.gz cif
cp ~/pdb/mmCIF/em/7emf.cif.gz cif
cp ~/pdb/mmCIF/en/7enj.cif.gz cif
cp ~/pdb/mmCIF/ep/7epu.cif.gz cif
cp ~/pdb/mmCIF/es/7es4.cif.gz cif
cp ~/pdb/mmCIF/es/7esr.cif.gz cif
cp ~/pdb/mmCIF/ey/7ey7.cif.gz cif
cp ~/pdb/mmCIF/fc/7fc9.cif.gz cif
cp ~/pdb/mmCIF/jg/7jgr.cif.gz cif
cp ~/pdb/mmCIF/jg/7jgs.cif.gz cif
cp ~/pdb/mmCIF/jh/7jh5.cif.gz cif
cp ~/pdb/mmCIF/jh/7jh6.cif.gz cif
cp ~/pdb/mmCIF/jk/7jk6.cif.gz cif
cp ~/pdb/mmCIF/jl/7jlv.cif.gz cif
cp ~/pdb/mmCIF/jp/7jpp.cif.gz cif
cp ~/pdb/mmCIF/jq/7jq6.cif.gz cif
cp ~/pdb/mmCIF/jr/7jr7.cif.gz cif
cp ~/pdb/mmCIF/jw/7jw1.cif.gz cif
cp ~/pdb/mmCIF/k2/7k2t.cif.gz cif
cp ~/pdb/mmCIF/kh/7khw.cif.gz cif
cp ~/pdb/mmCIF/ku/7kut.cif.gz cif
cp ~/pdb/mmCIF/l1/7l1q.cif.gz cif
cp ~/pdb/mmCIF/l1/7l1r.cif.gz cif
cp ~/pdb/mmCIF/l1/7l1s.cif.gz cif
cp ~/pdb/mmCIF/lb/7lb8.cif.gz cif
cp ~/pdb/mmCIF/lc/7lcc.cif.gz cif
cp ~/pdb/mmCIF/lk/7lkp.cif.gz cif
cp ~/pdb/mmCIF/lk/7lkz.cif.gz cif
cp ~/pdb/mmCIF/ln/7ln2.cif.gz cif
cp ~/pdb/mmCIF/lq/7lq4.cif.gz cif
cp ~/pdb/mmCIF/lu/7luv.cif.gz cif
cp ~/pdb/mmCIF/m1/7m1q.cif.gz cif
cp ~/pdb/mmCIF/m3/7m33.cif.gz cif
cp ~/pdb/mmCIF/m6/7m68.cif.gz cif
cp ~/pdb/mmCIF/m6/7m69.cif.gz cif
cp ~/pdb/mmCIF/m9/7m99.cif.gz cif
cp ~/pdb/mmCIF/m9/7m9a.cif.gz cif
cp ~/pdb/mmCIF/m9/7m9b.cif.gz cif
cp ~/pdb/mmCIF/m9/7m9c.cif.gz cif
cp ~/pdb/mmCIF/mb/7mbw.cif.gz cif
cp ~/pdb/mmCIF/mb/7mbz.cif.gz cif
cp ~/pdb/mmCIF/mc/7mc0.cif.gz cif
cp ~/pdb/mmCIF/mc/7mca.cif.gz cif
cp ~/pdb/mmCIF/mc/7mcs.cif.gz cif
cp ~/pdb/mmCIF/md/7mdx.cif.gz cif
cp ~/pdb/mmCIF/md/7mdy.cif.gz cif
cp ~/pdb/mmCIF/me/7met.cif.gz cif
cp ~/pdb/mmCIF/me/7mew.cif.gz cif
cp ~/pdb/mmCIF/mi/7mi6.cif.gz cif
cp ~/pdb/mmCIF/mi/7mi8.cif.gz cif
cp ~/pdb/mmCIF/mi/7mit.cif.gz cif
cp ~/pdb/mmCIF/mj/7mjo.cif.gz cif
cp ~/pdb/mmCIF/mj/7mjp.cif.gz cif
cp ~/pdb/mmCIF/mj/7mjq.cif.gz cif
cp ~/pdb/mmCIF/mp/7mpe.cif.gz cif
cp ~/pdb/mmCIF/mq/7mqj.cif.gz cif
cp ~/pdb/mmCIF/mu/7mu0.cif.gz cif
cp ~/pdb/mmCIF/n5/7n58.cif.gz cif
cp ~/pdb/mmCIF/n5/7n59.cif.gz cif
cp ~/pdb/mmCIF/n5/7n5a.cif.gz cif
cp ~/pdb/mmCIF/n5/7n5b.cif.gz cif
cp ~/pdb/mmCIF/n6/7n6i.cif.gz cif
cp ~/pdb/mmCIF/nd/7ndf.cif.gz cif
cp ~/pdb/mmCIF/nh/7nhr.cif.gz cif
cp ~/pdb/mmCIF/ni/7niu.cif.gz cif
cp ~/pdb/mmCIF/ni/7niv.cif.gz cif
cp ~/pdb/mmCIF/ni/7niw.cif.gz cif
cp ~/pdb/mmCIF/nj/7njn.cif.gz cif
cp ~/pdb/mmCIF/nm/7nmq.cif.gz cif
cp ~/pdb/mmCIF/nn/7nnt.cif.gz cif
cp ~/pdb/mmCIF/nn/7nnu.cif.gz cif
cp ~/pdb/mmCIF/ns/7ns4.cif.gz cif
cp ~/pdb/mmCIF/nv/7nvr.cif.gz cif
cp ~/pdb/mmCIF/ny/7nyw.cif.gz cif
cp ~/pdb/mmCIF/ny/7nyx.cif.gz cif
cp ~/pdb/mmCIF/o0/7o0y.cif.gz cif
cp ~/pdb/mmCIF/o1/7o10.cif.gz cif
cp ~/pdb/mmCIF/o1/7o11.cif.gz cif
cp ~/pdb/mmCIF/o1/7o12.cif.gz cif
cp ~/pdb/mmCIF/o1/7o14.cif.gz cif
cp ~/pdb/mmCIF/o1/7o15.cif.gz cif
cp ~/pdb/mmCIF/o1/7o16.cif.gz cif
cp ~/pdb/mmCIF/o1/7o17.cif.gz cif
cp ~/pdb/mmCIF/o3/7o3w.cif.gz cif
cp ~/pdb/mmCIF/o3/7o3x.cif.gz cif
cp ~/pdb/mmCIF/o3/7o3y.cif.gz cif
cp ~/pdb/mmCIF/o9/7o9w.cif.gz cif
cp ~/pdb/mmCIF/oc/7ocy.cif.gz cif
cp ~/pdb/mmCIF/ot/7otg.cif.gz cif
cp ~/pdb/mmCIF/ot/7oti.cif.gz cif
cp ~/pdb/mmCIF/ot/7otj.cif.gz cif
cp ~/pdb/mmCIF/ot/7oto.cif.gz cif
cp ~/pdb/mmCIF/ou/7ou0.cif.gz cif
cp ~/pdb/mmCIF/ou/7ou2.cif.gz cif
cp ~/pdb/mmCIF/ou/7ou4.cif.gz cif
cp ~/pdb/mmCIF/ow/7ow8.cif.gz cif
cp ~/pdb/mmCIF/oz/7oz1.cif.gz cif
cp ~/pdb/mmCIF/p0/7p03.cif.gz cif
cp ~/pdb/mmCIF/p0/7p04.cif.gz cif
cp ~/pdb/mmCIF/p0/7p05.cif.gz cif
cp ~/pdb/mmCIF/p0/7p06.cif.gz cif
cp ~/pdb/mmCIF/p2/7p2p.cif.gz cif
cp ~/pdb/mmCIF/p2/7p2y.cif.gz cif
cp ~/pdb/mmCIF/p3/7p34.cif.gz cif
cp ~/pdb/mmCIF/p3/7p3n.cif.gz cif
cp ~/pdb/mmCIF/p3/7p3r.cif.gz cif
cp ~/pdb/mmCIF/p3/7p3w.cif.gz cif
cp ~/pdb/mmCIF/pp/7ppj.cif.gz cif
cp ~/pdb/mmCIF/ps/7psl.cif.gz cif
cp ~/pdb/mmCIF/ps/7psm.cif.gz cif
cp ~/pdb/mmCIF/ps/7psn.cif.gz cif
cp ~/pdb/mmCIF/pz/7pzc.cif.gz cif
cp ~/pdb/mmCIF/q2/7q2x.cif.gz cif
cp ~/pdb/mmCIF/q2/7q2y.cif.gz cif
cp ~/pdb/mmCIF/qa/7qa8.cif.gz cif
cp ~/pdb/mmCIF/qh/7qhm.cif.gz cif
cp ~/pdb/mmCIF/qp/7qpg.cif.gz cif
cp ~/pdb/mmCIF/qv/7qv8.cif.gz cif
cp ~/pdb/mmCIF/r7/7r7j.cif.gz cif
cp ~/pdb/mmCIF/r8/7r87.cif.gz cif
cp ~/pdb/mmCIF/r8/7r88.cif.gz cif
cp ~/pdb/mmCIF/r8/7r89.cif.gz cif
cp ~/pdb/mmCIF/r8/7r8a.cif.gz cif
cp ~/pdb/mmCIF/r8/7r8b.cif.gz cif
cp ~/pdb/mmCIF/r8/7r8c.cif.gz cif
cp ~/pdb/mmCIF/r8/7r8d.cif.gz cif
cp ~/pdb/mmCIF/r8/7r8e.cif.gz cif
cp ~/pdb/mmCIF/ro/7roq.cif.gz cif
cp ~/pdb/mmCIF/rr/7rr9.cif.gz cif
cp ~/pdb/mmCIF/rr/7rra.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5c.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5k.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5v.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5x.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5y.cif.gz cif
cp ~/pdb/mmCIF/s5/7s5z.cif.gz cif
cp ~/pdb/mmCIF/s6/7s60.cif.gz cif
cp ~/pdb/mmCIF/s6/7s61.cif.gz cif
cp ~/pdb/mmCIF/se/7sel.cif.gz cif
cp ~/pdb/mmCIF/sf/7sfk.cif.gz cif
cp ~/pdb/mmCIF/sg/7sgz.cif.gz cif
cp ~/pdb/mmCIF/sh/7sh2.cif.gz cif
cp ~/pdb/mmCIF/sh/7shm.cif.gz cif
cp ~/pdb/mmCIF/sh/7shn.cif.gz cif
cp ~/pdb/mmCIF/sh/7shs.cif.gz cif
cp ~/pdb/mmCIF/sj/7sjr.cif.gz cif
cp ~/pdb/mmCIF/sm/7smo.cif.gz cif
cp ~/pdb/mmCIF/st/7st9.cif.gz cif
cp ~/pdb/mmCIF/st/7stb.cif.gz cif
cp ~/pdb/mmCIF/sv/7sv7.cif.gz cif
cp ~/pdb/mmCIF/sv/7svd.cif.gz cif
cp ~/pdb/mmCIF/sv/7svr.cif.gz cif
cp ~/pdb/mmCIF/sw/7swl.cif.gz cif
cp ~/pdb/mmCIF/t0/7t0v.cif.gz cif
cp ~/pdb/mmCIF/t3/7t3i.cif.gz cif
cp ~/pdb/mmCIF/t5/7t54.cif.gz cif
cp ~/pdb/mmCIF/t5/7t55.cif.gz cif
cp ~/pdb/mmCIF/t5/7t56.cif.gz cif
cp ~/pdb/mmCIF/t5/7t57.cif.gz cif
cp ~/pdb/mmCIF/ta/7tac.cif.gz cif
cp ~/pdb/mmCIF/ta/7tao.cif.gz cif
cp ~/pdb/mmCIF/tb/7tbw.cif.gz cif
cp ~/pdb/mmCIF/tb/7tby.cif.gz cif
cp ~/pdb/mmCIF/tb/7tbz.cif.gz cif
cp ~/pdb/mmCIF/tc/7tc0.cif.gz cif
cp ~/pdb/mmCIF/tc/7tcg.cif.gz cif
cp ~/pdb/mmCIF/tc/7tch.cif.gz cif
cp ~/pdb/mmCIF/ti/7tib.cif.gz cif
cp ~/pdb/mmCIF/tn/7tn2.cif.gz cif
cp ~/pdb/mmCIF/v2/7v2b.cif.gz cif
cp ~/pdb/mmCIF/vc/7vcs.cif.gz cif
cp ~/pdb/mmCIF/vg/7vgf.cif.gz cif
cp ~/pdb/mmCIF/vl/7vlr.cif.gz cif
cp ~/pdb/mmCIF/vl/7vls.cif.gz cif
cp ~/pdb/mmCIF/vl/7vlt.cif.gz cif
cp ~/pdb/mmCIF/vl/7vlu.cif.gz cif
cp ~/pdb/mmCIF/vu/7vuf.cif.gz cif
cp ~/pdb/mmCIF/vu/7vuk.cif.gz cif
cp ~/pdb/mmCIF/vw/7vwc.cif.gz cif
cp ~/pdb/mmCIF/vx/7vx8.cif.gz cif
cp ~/pdb/mmCIF/vz/7vzb.cif.gz cif
cp ~/pdb/mmCIF/w0/7w01.cif.gz cif
cp ~/pdb/mmCIF/w0/7w02.cif.gz cif
cp ~/pdb/mmCIF/w4/7w4o.cif.gz cif
cp ~/pdb/mmCIF/w4/7w4p.cif.gz cif
cp ~/pdb/mmCIF/z1/7z17.cif.gz cif
cp ~/pdb/mmCIF/z1/7z18.cif.gz cif
cp ~/pdb/mmCIF/z1/7z19.cif.gz cif
cp ~/pdb/mmCIF/z6/7z67.cif.gz cif
cp ~/pdb/mmCIF/z6/7z6h.cif.gz cif
